(* ===================================================================== *)
(*  IDM_Apriori.v — the Richardson A-PRIORI stability certificate, machine-  *)
(*  checked and axiom-free over ℚ (Coq 8.20; Print Assumptions = Closed      *)
(*  under the global context).  By Yaoharee Lahtee.                         *)
(*                                                                          *)
(*  `refine_stable` (formal/IDM_Certified.v) is the A-POSTERIORI certificate: *)
(*  it ASSUMES the observed contraction hypothesis                           *)
(*      ∀k, |s(k+1)| ≤ ρ·|s k|                                               *)
(*  (which the code establishes by watching the actual refinement gaps —      *)
(*  tools/certified_readout.py, `richardson_certified` / integral_stable) and *)
(*  concludes the stability bound (1−ρ)·|Σ gaps| ≤ |s N|.                     *)
(*                                                                          *)
(*  This file supplies the A-PRIORI side (THEOREM.md open item #1): DECIDE the *)
(*  contraction from the FORM of the sequence up front, so the hypothesis is  *)
(*  discharged once by structure rather than checked gap-by-gap on data.      *)
(*                                                                          *)
(*    apriori_multiplicative_contracts — if the gaps are generated by a        *)
(*        multiplier form s(k+1) = m k · s k with every |m k| ≤ ρ, the         *)
(*        contraction hypothesis holds for ALL k (not just the observed ones). *)
(*    apriori_geometric_contracts — the closed-form leading-term instance:     *)
(*        s k = a·qᵏ with |q| ≤ ρ.  This is the Richardson leading error term. *)
(*    apriori_stable — chains the multiplier form straight into refine_stable: *)
(*        stability decided from the form, with no gap observation.            *)
(*    richardson_apriori_contracts / richardson_apriori_stable — the Richardson *)
(*        specialisation: a method of ORDER p with step-halving has column-gap  *)
(*        ratio ρ = 2⁻ᵖ, a constant known from the order ALONE.  So order p ⇒  *)
(*        ρ = 2⁻ᵖ ≤ 1 ⇒ certified-stable, up front.                            *)
(*                                                                          *)
(*  Honest fence: a real Richardson tableau's gaps are DOMINATED by this       *)
(*  geometric envelope (the leading uncancelled term), higher-order terms      *)
(*  only making them contract faster; the map "method order p ⇒ ρ = 2⁻ᵖ" is    *)
(*  the standard Richardson fact, its numeric side already exercised by the    *)
(*  a-posteriori tests.  What is machine-checked here is the ℚ-algebra: the     *)
(*  form ⇒ contraction ⇒ refine_stable bound implication, axiom-free.          *)
(* ===================================================================== *)

Require Import QArith.
Require Import Qabs.
Require Import Setoid.
Require Import IDM_Certified.        (* qpow, tailsum, refine_stable *)

Local Open Scope Q_scope.

(* ---- a-priori certificate 1: the multiplier form contracts for ALL k. ---- *)
Theorem apriori_multiplicative_contracts :
  forall (rho : Q) (m s : nat -> Q),
    (forall k, Qabs (m k) <= rho) ->
    (forall k, s (S k) == m k * s k) ->
    (forall k, Qabs (s (S k)) <= rho * Qabs (s k)).
Proof.
  intros rho m s Hm Hs k.
  rewrite (Hs k).                              (* |s(S k)| = |m k * s k| *)
  rewrite Qabs_Qmult.                          (* = |m k| * |s k|        *)
  apply Qmult_le_compat_r; [ apply Hm | apply Qabs_nonneg ].
Qed.

(* ---- a-priori certificate 2: the geometric closed form (Richardson leading  *)
(*      term) s k = a·qᵏ contracts with ratio |q|. --------------------------- *)
Theorem apriori_geometric_contracts :
  forall (rho a q : Q) (s : nat -> Q),
    Qabs q <= rho ->
    (forall k, s k == a * qpow q k) ->
    (forall k, Qabs (s (S k)) <= rho * Qabs (s k)).
Proof.
  intros rho a q s Hq Hs k.
  assert (Hstep : s (S k) == q * s k).
  { rewrite (Hs (S k)), (Hs k). simpl. ring. }
  rewrite Hstep, Qabs_Qmult.
  apply Qmult_le_compat_r; [ exact Hq | apply Qabs_nonneg ].
Qed.

(* ---- a-priori stability: the multiplier form feeds refine_stable directly,  *)
(*      giving the finite stability bound with NO gap observation. ----------- *)
Theorem apriori_stable :
  forall (rho : Q) (m s : nat -> Q) (N M : nat),
    rho <= 1 ->
    (forall k, Qabs (m k) <= rho) ->
    (forall k, s (S k) == m k * s k) ->
    (1 - rho) * Qabs (tailsum s N M) <= Qabs (s N).
Proof.
  intros rho m s N M Hle Hm Hs.
  apply refine_stable; [ exact Hle |].
  exact (apriori_multiplicative_contracts rho m s Hm Hs).
Qed.

(* ---------------------------------------------------------------------- *)
(*  The Richardson specialisation: order p ⇒ ratio 2⁻ᵖ, known up front.      *)
(* ---------------------------------------------------------------------- *)
Definition richardson_ratio (p : nat) : Q := qpow (1 # 2) p.

Lemma half_nonneg : 0 <= (1 # 2). Proof. apply Qle_bool_imp_le; reflexivity. Qed.

Lemma richardson_ratio_nonneg : forall p, 0 <= richardson_ratio p.
Proof.
  induction p as [| k IH]; unfold richardson_ratio in *; simpl.
  - apply Qle_bool_imp_le; reflexivity.               (* 0 <= 1 *)
  - apply Qle_trans with (y := (1 # 2) * 0).
    + rewrite Qmult_0_r. apply Qle_refl.
    + apply Qmult_le_l_nonneg; [ apply half_nonneg | exact IH ].
Qed.

Lemma richardson_ratio_le_one : forall p, richardson_ratio p <= 1.
Proof.
  induction p as [| k IH]; unfold richardson_ratio in *; simpl.
  - apply Qle_refl.                                    (* 1 <= 1 *)
  - (* (1/2) * qpow(1/2) k <= 1, from qpow k in [0,1] *)
    apply Qle_trans with (y := (1 # 2) * 1).
    + apply Qmult_le_l_nonneg; [ apply half_nonneg | exact IH ].
    + apply Qle_bool_imp_le; reflexivity.              (* (1#2)*1 <= 1 *)
Qed.

Theorem richardson_apriori_contracts :
  forall (p : nat) (a : Q) (s : nat -> Q),
    (forall k, s k == a * qpow (richardson_ratio p) k) ->
    (forall k, Qabs (s (S k)) <= richardson_ratio p * Qabs (s k)).
Proof.
  intros p a s Hs.
  apply (apriori_geometric_contracts (richardson_ratio p) a (richardson_ratio p) s); [| exact Hs ].
  rewrite (Qabs_pos (richardson_ratio p)); [ apply Qle_refl | apply richardson_ratio_nonneg ].
Qed.

Theorem richardson_apriori_stable :
  forall (p : nat) (a : Q) (s : nat -> Q) (N M : nat),
    (forall k, s k == a * qpow (richardson_ratio p) k) ->
    (1 - richardson_ratio p) * Qabs (tailsum s N M) <= Qabs (s N).
Proof.
  intros p a s N M Hs.
  apply refine_stable; [ apply richardson_ratio_le_one |].
  exact (richardson_apriori_contracts p a s Hs).
Qed.

(* sanity: the order-2 Richardson ratio is exactly 1/4 (a computed readout).   *)
Example richardson_ratio_2 : richardson_ratio 2 == 1 # 4.
Proof. reflexivity. Qed.
