"""Consistency-grading support package.

Read-only over registry/*.json, registry/LINEAGE.jsonl, and the seven
ops/clearing/findings_<dimension>.json files the equation-clearing auditors
already produced (each generated by ops/clearing/audit_<dimension>.py).
This package writes nothing itself; scripts/compute_consistency.py is the
only writer, and it writes only under registry/consistency/.
"""
