#!/usr/bin/env python3
"""Generate ops/clearing/NEEDS_RULING.md from the seven findings_<dimension>.json
files: every confirmed finding NOT applied by scripts/v18_clearing_fixes.py
(i.e. every finding marked `mechanical: false`, or carrying `status:
"needs_ruling"`, or fix class C/D), grouped founder-only (class D) vs
registrar (class B/C still needing a reader clearance or ruling before the
one permitted fix script may touch anything). Read-only over
ops/clearing/findings_*.json; writes only ops/clearing/NEEDS_RULING.md.
Idempotent -- re-run any time the findings files change.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.clearing import readout as R

OUT = R.ROOT / "ops" / "clearing" / "NEEDS_RULING.md"


def fix_class(f: dict) -> str:
    pf = f.get("proposed_fix")
    if isinstance(pf, dict) and pf.get("class"):
        return pf["class"]
    return f.get("class") or "?"


def needs_ruling(f: dict) -> bool:
    return (not f.get("mechanical", False)) or f.get("status") == "needs_ruling" or fix_class(f) in ("C", "D")


def main():
    rows = []
    for dim in R.DIMENSIONS:
        for f in R.load_findings(dim)["findings"]:
            if needs_ruling(f):
                rows.append((dim, f))

    founder_only = [(d, f) for d, f in rows if fix_class(f) == "D"]
    registrar = [(d, f) for d, f in rows if fix_class(f) != "D"]

    lines = [
        "# Findings awaiting a ruling (docs/CONSISTENCY_SPEC_v0_1.md sec.5)",
        "",
        "Generated by scripts/clearing/write_needs_ruling.py from the seven",
        "ops/clearing/findings_<dimension>.json files -- every confirmed finding",
        "scripts/v18_clearing_fixes.py did NOT apply, because it is not class A/B",
        "with no outstanding ruling, or it is marked `mechanical: false`. Regenerate",
        "this file (never hand-edit it) whenever a dimension's findings file changes",
        "or a ruling resolves an item below.",
        "",
        f"Founder-only (fix class D -- the meaning of a ladder word, raising any tier,",
        f"any root-layer `parents` change, or anything else the spec sec.5 table reserves",
        f"to the founder): **{len(founder_only)}** open.",
        "",
        f"Registrar (fix class B/C still needing a reader clearance row or a named",
        f"ruling before the one permitted fix script may touch anything): "
        f"**{len(registrar)}** open.",
        "",
        "---",
        "",
        "## Founder-only (class D)",
        "",
    ]

    def render_group(group):
        out = []
        for dim, f in sorted(group, key=lambda df: df[1]["id"]):
            claim = f.get("claim", "")
            codes = R.extract_codes(f)
            code_note = f"{len(codes)} code(s): {', '.join(codes[:6])}" + (", ..." if len(codes) > 6 else "")
            fix = f.get("proposed_fix")
            action = fix.get("action") if isinstance(fix, dict) else None
            ruling_ref = fix.get("ruling_ref") if isinstance(fix, dict) else None
            out.append(f"### `{f['id']}` ({dim}, class {fix_class(f)})")
            out.append("")
            out.append(claim)
            out.append("")
            out.append(f"- codes: {code_note}")
            if action:
                out.append(f"- proposed fix: {action}")
            if ruling_ref:
                out.append(f"- ruling_ref: {ruling_ref}")
            out.append("")
        return out

    lines += render_group(founder_only)
    lines.append("## Registrar (class B/C)")
    lines.append("")
    lines += render_group(registrar)

    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(founder_only)} founder-only, {len(registrar)} registrar)")


if __name__ == "__main__":
    main()
