(* MRC_Prelude.v -- BBL-182/T8 shared-device prelude, generated by scripts/bbl182_split_coq.py from the pre-split MRC_*.v family top matter (originals preserved in coq/canonical/_mrc_pre_split/). Every generated per-code file that consumes one of these devices `From MRC Require Import MRC_Prelude.`; every other generated file also carries the Require harmlessly (unused-import, not an error). No new proof content: byte-identical device bodies lifted from the pre-split sources, cited below. *)

From Coq Require Import QArith.
From Coq Require Import Qminmax.
From Coq Require Import Lqa.
From Coq Require Import ZArith.
From Coq Require Import Lia.
From Coq Require Import List.
Import ListNotations.
Set Implicit Arguments.
Require Import MR.MR_WorldSystem.

(* -- from epistemic-reading (shared non-collapse device, consumed by CAN-011/032/037/219/221/223-229) -- *)
Definition notions_pairwise_distinct {T : Type} (code : T -> nat) : Prop :=
  forall a b : T, code a = code b -> a = b.

(* -- from method-reading-a (shared devices, consumed by CAN-165/CAN-181/CAN-194; CAN-216 keeps its own local re-declaration per the family docstring) -- *)
Section MRFactorization.
  Variables X Y Z : Type.
  Variable R : X -> Y.
  Variable Phi : X -> Z.

  (** Fiber-constancy: [Phi] cannot distinguish two [X]-points [R] itself
      does not distinguish. *)
  Definition mr_admissible : Prop := forall x x', R x = R x' -> Phi x = Phi x'.

  Variable Rinv_dec : forall y : Y, {x : X | R x = y} + (forall x, R x <> y).
  Variable default : Z.

  (** The factored map g : Y -> Z, built by finite/decidable search over
      the (declared, per-[y]) preimage witness — never by unbounded
      choice. *)
  Definition mr_g_of (y : Y) : Z :=
    match Rinv_dec y with
    | inl (exist _ x _) => Phi x
    | inr _ => default
    end.

  (** The Factorization Theorem: admissibility (fiber-constancy) is
      exactly the condition under which [Phi] factors as [g o R]. *)
  Theorem mr_factorization_thm : mr_admissible -> forall x, Phi x = mr_g_of (R x).
  Proof.
    intros Hadm x. unfold mr_g_of.
    destruct (Rinv_dec (R x)) as [[x' Hx'] | Hno].
    - apply Hadm. symmetry. exact Hx'.
    - exfalso. apply (Hno x). reflexivity.
  Qed.
End MRFactorization.

Lemma mr_no_factorization_when_fiber_varies :
  forall (X Y Z : Type) (K : X -> Y) (C : X -> Z) (x1 x2 : X),
    K x1 = K x2 -> C x1 <> C x2 -> ~ exists G : Y -> Z, forall x, C x = G (K x).
Proof.
  intros X Y Z K C x1 x2 Heq Hne [G HG].
  apply Hne. rewrite (HG x1), (HG x2), Heq. reflexivity.
Qed.

Definition mr_qmin_fold (l : list Q) (d : Q) : Q := fold_right Qmin d l.

Lemma mr_qmin_fold_le : forall (l : list Q) (d x : Q), In x l -> mr_qmin_fold l d <= x.
Proof.
  induction l as [| a rest IH]; intros d x Hin.
  - simpl in Hin. contradiction.
  - simpl in Hin. destruct Hin as [Heq | Hin'].
    + subst. unfold mr_qmin_fold. simpl. apply Q.le_min_l.
    + unfold mr_qmin_fold. simpl.
      apply Qle_trans with (y := mr_qmin_fold rest d).
      * apply Q.le_min_r.
      * apply IH. exact Hin'.
Qed.

Definition mr_qsum (l : list Q) : Q := fold_right Qplus 0 l.

Lemma mr_qsum_nonneg : forall l, (forall y, In y l -> 0 <= y) -> 0 <= mr_qsum l.
Proof.
  induction l as [| a rest IH]; intro Hnn.
  - unfold mr_qsum. simpl. lra.
  - unfold mr_qsum in *. simpl.
    assert (Ha : 0 <= a) by (apply Hnn; left; reflexivity).
    assert (Hrest : 0 <= fold_right Qplus 0 rest)
      by (apply IH; intros y Hy; apply Hnn; right; exact Hy).
    lra.
Qed.

Lemma mr_qsum_ge_member : forall (l : list Q) (x : Q),
  In x l -> (forall y, In y l -> 0 <= y) -> x <= mr_qsum l.
Proof.
  induction l as [| a rest IH]; intros x Hin Hnn.
  - simpl in Hin. contradiction.
  - simpl in Hin. unfold mr_qsum in *. simpl. destruct Hin as [Heq | Hin'].
    + subst.
      assert (Hrest : 0 <= fold_right Qplus 0 rest).
      { apply mr_qsum_nonneg. intros y Hy. apply Hnn. right. exact Hy. }
      lra.
    + assert (Ha : 0 <= a) by (apply Hnn; left; reflexivity).
      assert (Hle : x <= fold_right Qplus 0 rest)
        by (apply IH; [exact Hin' | intros y Hy; apply Hnn; right; exact Hy]).
      lra.
Qed.

(* -- from world-system-reading (shared witness, consumed by CAN-146/147/148/153/154/160) -- *)
Theorem CAN_ws_generic_rise_not_entail_rise :
  exists (f g : nat -> Q) (t : nat),
    0 < MR_WorldSystem.ddiff f t /\ ~ (0 < MR_WorldSystem.ddiff g t).
Proof.
  exists (fun n => match n with O => 0 | S _ => 1 end), (fun _ => 0), O.
  unfold MR_WorldSystem.ddiff. simpl. split; lra.
Qed.

(* -- from method-reading-b (shared 50-constructor enumeration, consumed by CAN-230..256) -- *)
Inductive CAN2xx_MethodNotion :=
  | CAN2xx_Credit | CAN2xx_EpistemicValue
  | CAN2xx_Friction | CAN2xx_Fellowship
  | CAN2xx_SelfExperience | CAN2xx_GeneralEvidence
  | CAN2xx_PositionalAccess | CAN2xx_PopulationAuthority
  | CAN2xx_CommunityTrust | CAN2xx_Representativeness
  | CAN2xx_DVP | CAN2xx_K2
  | CAN2xx_ManyModels | CAN2xx_Independence
  | CAN2xx_MechanicalValidity | CAN2xx_SemanticValidity
  | CAN2xx_SourceExistence | CAN2xx_ClaimSupport
  | CAN2xx_Friendship | CAN2xx_IndependentEvidence
  | CAN2xx_Correspondence | CAN2xx_PeerReview
  | CAN2xx_IntellectualAffinity | CAN2xx_Truth
  | CAN2xx_ActivationAction | CAN2xx_CreditEvent
  | CAN2xx_RawSpeedDown | CAN2xx_VCDown
  | CAN2xx_LH | CAN2xx_LV
  | CAN2xx_MA_n | CAN2xx_ThetaE
  | CAN2xx_MultiAIConsensus | CAN2xx_GeographicCompleteness
  | CAN2xx_DoubleBlind | CAN2xx_Requirement
  | CAN2xx_K2Global | CAN2xx_K2Thai
  | CAN2xx_InterventionCreator | CAN2xx_SoleEvaluator
  | CAN2xx_PracticeExperience | CAN2xx_PopulationEvidence
  | CAN2xx_At | CAN2xx_CtScholarly
  | CAN2xx_MAttention | CAN2xx_MTruth | CAN2xx_MK2
  | CAN2xx_NoHumanAvailable | CAN2xx_ResearchStop
  | CAN2xx_Prestige | CAN2xx_APCApproval
  | CAN2xx_DisclosurePenalty | CAN2xx_Concealment
  | CAN2xx_AIContribution | CAN2xx_EpistemicResponsibility.

