#!/usr/bin/env python3
"""
site/build_site.py — static HTML for the generated Toledo library.

Reads site/index.json + registry/TOLEDO.json + vault/<code-safe>.md (written by
scripts/toledo_build.py) and writes site/index.html (client-side search over
index.json) plus one page per code at site/<code-safe>.html. No external assets,
no network, no build step beyond stdlib Python.
"""
from __future__ import annotations

import argparse
import html
import json
import pathlib
import re

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent

STYLE = """
:root { color-scheme: light dark; }
body { font-family: Georgia, "Noto Serif", serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem;
       background: #fbfbf9; color: #1a1a1a; }
@media (prefers-color-scheme: dark) { body { background: #15171a; color: #e8e8e6; } a { color: #8ab4f8; } }
h1, h2 { font-family: -apple-system, "Segoe UI", sans-serif; }
code, pre { font-family: "DejaVu Sans Mono", monospace; }
table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
th, td { border: 1px solid #8883; padding: 0.35rem 0.6rem; text-align: left; font-size: 0.92rem; }
#search { width: 100%; padding: 0.5rem; font-size: 1rem; margin-bottom: 1rem; box-sizing: border-box; }
.tier, .status { display: inline-block; padding: 0.05rem 0.4rem; border-radius: 3px; background: #8882; font-size: 0.8rem; }
.breadcrumb { font-size: 0.85rem; opacity: 0.8; }
a.code-link { text-decoration: none; border-bottom: 1px dotted; }
footer { margin-top: 3rem; font-size: 0.8rem; opacity: 0.7; }
"""


def code_safe(code: str) -> str:
    return code.replace("/", "__").replace(".", "_")


def load_json(path: pathlib.Path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def md_to_minimal_html(md_text: str, code_lookup: set) -> str:
    """Very small Markdown->HTML: headings, code fences, [[wikilinks]], lists, paragraphs.
    Not a general Markdown engine — just enough for the vault pages this repo generates."""
    lines = md_text.splitlines()
    out = []
    in_code = False
    for line in lines:
        if line.startswith("```"):
            if not in_code:
                lang = line[3:].strip()
                out.append(f'<pre><code class="lang-{html.escape(lang)}">')
                in_code = True
            else:
                out.append("</code></pre>")
                in_code = False
            continue
        if in_code:
            out.append(html.escape(line))
            continue
        m = re.match(r"^(#{1,6})\s+(.*)$", line)
        if m:
            level = len(m.group(1))
            out.append(f"<h{level}>{html.escape(m.group(2))}</h{level}>")
            continue
        if line.strip().startswith("- "):
            out.append("<li>" + _inline(line.strip()[2:], code_lookup) + "</li>")
            continue
        if not line.strip():
            out.append("")
            continue
        out.append("<p>" + _inline(line, code_lookup) + "</p>")
    return "\n".join(out)


def _inline(text: str, code_lookup: set) -> str:
    def wikilink(m):
        target = m.group(1)
        label = target
        return f'<a class="code-link" href="{html.escape(target)}.html">{html.escape(label)}</a>'

    text = re.sub(r"\[\[([^\]]+)\]\]", wikilink, text)
    text = re.sub(r"`([^`]+)`", lambda m: f"<code>{html.escape(m.group(1))}</code>", text)
    return text


PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{code} — Toledo</title>
<style>{style}</style>
</head>
<body>
<p class="breadcrumb"><a href="index.html">Toledo</a> / {code}</p>
<h1>{code}</h1>
<p><span class="tier">{tier}</span> <span class="status">{status}</span></p>
{mathml_block}
{body}
<footer>Generated by site/build_site.py — do not hand-edit.</footer>
</body>
</html>
"""

INDEX_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Toledo — equation library</title>
<style>{style}</style>
</head>
<body>
<h1>Toledo</h1>
<p>Search {count} coded entries (statement, name, root, domain, tier).</p>
<input id="search" type="text" placeholder="find...">
<table id="results"><thead><tr><th>Code</th><th>Tier</th><th>Domain</th><th>Statement</th></tr></thead>
<tbody id="results-body"></tbody></table>
<script>
const TOLEDO_INDEX = {index_json};
const box = document.getElementById('search');
const body = document.getElementById('results-body');
function render(rows) {{
  body.innerHTML = rows.map(function(r) {{
    var href = r.code.replace(/\\//g, '__').replace(/\\./g, '_') + '.html';
    return '<tr><td><a href="' + href + '">' + r.code + '</a></td><td>' + (r.tier||'') +
           '</td><td>' + (r.domain||'') + '</td><td>' + (r.statement_plain||'').slice(0,80) + '</td></tr>';
  }}).join('');
}}
box.addEventListener('input', function() {{
  var q = box.value.toLowerCase();
  render(TOLEDO_INDEX.filter(function(r) {{
    return (r.code||'').toLowerCase().includes(q) || (r.object||'').toLowerCase().includes(q) ||
           (r.statement_plain||'').toLowerCase().includes(q) || (r.root||'').toLowerCase().includes(q);
  }}));
}});
render(TOLEDO_INDEX);
</script>
<footer>Generated by site/build_site.py — do not hand-edit.</footer>
</body>
</html>
"""


def build_site(out_root: pathlib.Path) -> dict:
    index_path = out_root / "site" / "index.json"
    toledo_path = out_root / "registry" / "TOLEDO.json"
    vault_dir = out_root / "vault"
    site_dir = out_root / "site"

    index_doc = load_json(index_path)
    toledo_doc = load_json(toledo_path)
    entries_by_code = {e["code"]: e for e in toledo_doc["canonical"]}
    code_lookup = {code_safe(c) for c in entries_by_code}

    site_dir.mkdir(parents=True, exist_ok=True)

    index_html = INDEX_TEMPLATE.format(
        style=STYLE, count=len(index_doc["entries"]),
        index_json=json.dumps(index_doc["entries"], ensure_ascii=False),
    )
    (site_dir / "index.html").write_text(index_html, encoding="utf-8")

    pages = []
    for code, e in entries_by_code.items():
        safe = code_safe(code)
        md_path = vault_dir / f"{safe}.md"
        body_html = md_to_minimal_html(md_path.read_text(encoding="utf-8"), code_lookup) if md_path.exists() else "<p><em>no vault page generated</em></p>"
        entry_json_path = out_root / "registry" / "entries" / f"{safe}.json"
        mathml_block = ""
        if entry_json_path.exists():
            entry_doc = load_json(entry_json_path)
            pres = entry_doc.get("presentation_mathml")
            if pres:
                mathml_block = f'<div class="mathml">{pres}</div>'
        page_html = PAGE_TEMPLATE.format(
            code=html.escape(code), style=STYLE,
            tier=html.escape(e.get("tier", "")), status=html.escape(e.get("status", "")),
            mathml_block=mathml_block, body=body_html,
        )
        (site_dir / f"{safe}.html").write_text(page_html, encoding="utf-8")
        pages.append(safe)

    return {"site_dir": str(site_dir), "pages": len(pages)}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-root", type=pathlib.Path, default=REPO_ROOT)
    ap.add_argument("--sample", action="store_true", help="build the sample_output/ tree instead")
    args = ap.parse_args(argv)
    out_root = (REPO_ROOT / "sample_output") if args.sample else args.out_root
    report = build_site(out_root)
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
