(******************************************************************************)
(* InfoSolidAngle.v — the n-sphere solid angles ωₙ, generated by 2π.          *)
(*                                                                            *)
(* Continuing the graph→geometry→values axis past 4π. The solid angle of the  *)
(* sphere S^d is A(d)=|S^d|, and the WHOLE family is generated by ONE turn 2π  *)
(* via the recurrence A(d) = (2π/(d−1))·A(d−2):                                *)
(*   |S^0|=2, |S^1|=2π, |S^2|=4π (= InfoGreen's Green's-function solid angle), *)
(*   |S^3|=2π², …  All are readout-invariants of the geometry the graph        *)
(*   induces; π is transcendental so it stays a symbolic +reals variable and   *)
(*   every result is universally quantified over it. readout-not-truth.        *)
(******************************************************************************)

Require Import QArith.
Require Import Coq.micromega.Psatz.
Require Import Coq.micromega.Lqa.
Require Import Coq.ZArith.ZArith.

Module InfoSolidAngle.
  Open Scope Q_scope.
  Definition Qnat (n : nat) : Q := inject_Z (Z.of_nat n).

  (* A(d) = |S^d| (the sphere S^d ⊂ R^{d+1}); π symbolic. Recurrence A(d)=(2π/(d−1))·A(d−2). *)
  Fixpoint omega (d : nat) (pi : Q) : Q :=
    match d with
    | O => 2#1                                        (* |S^0| = 2 (two points)   *)
    | S O => (2#1)*pi                                 (* |S^1| = 2π (the circle)  *)
    | S (S k) => ((2#1)*pi / Qnat (S k)) * omega k pi (* A(d)=(2π/(d−1))·A(d−2)    *)
    end.

  (* (1) |S^1| = 2π — the fundamental turn. NOTE [definitional]: this is the base clause of `omega`
     stated for reference; it carries no proof content (reflexivity). The computed content is (3),(4). *)
  Theorem omega_S1_is_2pi : forall pi : Q, omega 1 pi == (2#1)*pi.
  Proof. intro pi. reflexivity. Qed.

  (* (2) the LADDER: 2π generates every solid angle — each is (2π/(d−1)) times the one two dimensions down.
     NOTE [definitional]: this restates the recurrence clause of `omega` (reflexivity) — it documents the
     2π-ladder structure; the non-trivial computed instances are omega_S2 (4π) and omega_S3 (2π²) below. *)
  Theorem omega_ladder : forall (k : nat) (pi : Q),
    omega (S (S k)) pi == ((2#1)*pi / Qnat (S k)) * omega k pi.
  Proof. intros k pi. reflexivity. Qed.

  (* (3) |S^2| = 4π — exactly InfoGreen's Green's-function solid angle (the 4π in Newton/Coulomb) *)
  Theorem omega_S2_is_4pi : forall pi : Q, omega 2 pi == (4#1)*pi.
  Proof. intro pi. unfold omega, Qnat.
    replace (inject_Z (Z.of_nat 1)) with (1:Q) by (vm_compute; reflexivity). field. Qed.

  (* (4) |S^3| = 2π² *)
  Theorem omega_S3_is_2pisq : forall pi : Q, omega 3 pi == (2#1)*pi*pi.
  Proof. intro pi. unfold omega, Qnat.
    replace (inject_Z (Z.of_nat 2)) with (2#1) by (vm_compute; reflexivity).
    replace (inject_Z (Z.of_nat 1)) with (1:Q) by (vm_compute; reflexivity). field. Qed.

End InfoSolidAngle.
