#!/usr/bin/env python3
"""toledo_mcp.cli — the `toledo` console-script CLI, S3 (mcp/DESIGN.md secs.
8/14).

Relationship to `scripts/toledo` (unchanged, untouched by this package):
that script is the registry-owning lane's own build-verification CLI — it
reads strictly `registry/TOLEDO.json` (a generated artifact) fresh on every
invocation, and stays exactly as it is. This module is a NEW, separate,
mcp-package-owned CLI that answers the same core verbs
(`find/show/ancestry/descendants/neighbours/by-root/by-domain/by-record/
export`) from the cached/indexed layer this package already built for the
MCP server (`cache.py`/`queries.py`), plus the verdict-aware subcommands
`scripts/toledo` never had (`check`, `status`, `proposals list/show`,
`register-proposal`, `index-status`, `show-verdict-rules`). Two genuine,
disclosed behavioural differences from `scripts/toledo`, not silently
presented as a drop-in replacement:

1. This CLI answers from `registry/CANONICAL.json` via the cache, so a code
   that is stale in `registry/TOLEDO.json` (not yet regenerated by `make
   build`) but present in `CANONICAL.json` is still found here.
2. `show`/`ancestry` and every row-list command attach the founder-rule
   `verdict` this package exists to enforce (2026-09-07: every equation
   must be looked up in Toledo before it is used) — `scripts/toledo show`
   only ever printed the bare entry.

`toledo_check`'s logic is intentionally duplicated here (not imported from
`server.py`) rather than the other way around: `server.py` imports THIS
module's TOON encoder (mcp/DESIGN.md sec. 7, graft B5/C7), so `cli.py` must
not import `server.py` back — that would be a cycle. Keep `cmd_check` in
step with `server.py`'s `toledo_check` by hand if either changes; both are
thin wrappers over the same `verdict.py`/`equivalence.py`/`core.py` engine,
so the two bodies are short enough that this is a real, checked, low-risk
duplication, not a maintenance trap.

Root resolution follows `paths.py`'s own rule (the `TOLEDO_ROOT` environment
variable, else the checkout `mcp/` sits in) — there is no `--out-root` flag
here, unlike `scripts/toledo`, because every subcommand reads through the
process-wide `cache.get_cache()` singleton, which resolves its own root the
same way on every call.

This CLI's own JSON output shape is NOT wrapped in the `{"ok","data","error"}`
envelope `mcp/DESIGN.md` sec. 3 specifies for the MCP tool surface (that
envelope is a `server.py`/S2 change to the tool-call contract) — each
subcommand prints the plain, natural shape for its own answer (a row list,
an entry+verdict dict, `null` for "not registered"), documented per command
below.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import Any

try:
    from . import cache as cache_mod
    from . import core, paths, proposals, regex_guard, verdict
except ImportError:
    # Allow `python3 mcp/toledo_mcp/cli.py ...` (run directly, not installed/
    # `-m`'d) the same way server.py already tolerates it.
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
    from toledo_mcp import cache as cache_mod
    from toledo_mcp import core, paths, proposals, regex_guard, verdict


# ---------------------------------------------------------------------------
# TOON encode/decode (mcp/DESIGN.md sec. 7/14, graft B5/C7) — a small,
# dependency-free implementation of TOON's TABULAR form only (github.com/
# toon-format/toon). Per this workspace's own `toon-format` skill: the
# verified win is token count on UNIFORM row data (~35% fewer tokens than
# JSON, measured with the official encoder + real tiktoken) — nothing about
# accuracy is claimed, and this form is never applied to a single nested
# entry or a non-uniform structure (see every `--format toon` call site
# below: only on compact-entry row lists, never on `show`/`check`/`status`).
# `server.py` (S2) imports this pair rather than re-implementing it, per
# mcp/DESIGN.md sec. 7's "a single implementation, not two".
# ---------------------------------------------------------------------------

_TOON_HEADER_RE = re.compile(r"^\[(\d+)\]\{(.*)\}:$")


def _toon_needs_quote(cell: str, delimiter: str) -> bool:
    return (
        delimiter in cell
        or '"' in cell
        or "\n" in cell
        or cell != cell.strip()
        or cell == ""
    )


def _toon_escape(value: Any, delimiter: str) -> str:
    if value is None:
        return ""
    cell = value if isinstance(value, str) else json.dumps(value, ensure_ascii=False)
    if _toon_needs_quote(cell, delimiter):
        cell = '"' + cell.replace('"', '""') + '"'
    return cell


def _toon_split_row(line: str, delimiter: str) -> list[str]:
    """Minimal CSV-style split honouring the double-quote escaping
    `_toon_escape` writes — no third-party csv-sniffing, this format only
    ever has to round-trip what this module itself wrote."""
    cells: list[str] = []
    cur: list[str] = []
    in_quotes = False
    i = 0
    while i < len(line):
        ch = line[i]
        if in_quotes:
            if ch == '"':
                if i + 1 < len(line) and line[i + 1] == '"':
                    cur.append('"')
                    i += 1
                else:
                    in_quotes = False
            else:
                cur.append(ch)
        else:
            if ch == '"':
                in_quotes = True
            elif ch == delimiter:
                cells.append("".join(cur))
                cur = []
            else:
                cur.append(ch)
        i += 1
    cells.append("".join(cur))
    return cells


def encode_toon(rows: list[dict], *, delimiter: str = ",") -> str:
    """Encode a list of UNIFORM dict rows (every row the same field set, no
    nested non-uniform structure) as one TOON tabular block:

        [N]{field1,field2,...}:
          v1,v2,...
          v1,v2,...

    Field order is taken from the first row. A field a later row lacks
    encodes as an empty cell (never a KeyError) — the compact-entry rows
    this package emits are already uniform by construction (`core._summarize`
    / `queries._summarize`), so this is a safety margin, not the expected
    path. Empty input encodes as the valid, explicit `[0]{}:` (no rows to
    infer a header from)."""
    if not rows:
        return "[0]{}:"
    fields = list(rows[0].keys())
    header = f"[{len(rows)}]{{{delimiter.join(fields)}}}:"
    lines = [header]
    for row in rows:
        cells = [_toon_escape(row.get(f), delimiter) for f in fields]
        lines.append("  " + delimiter.join(cells))
    return "\n".join(lines)


def decode_toon(text: str, *, delimiter: str = ",") -> list[dict]:
    """Decode a block `encode_toon` produced. This package only ever emits
    TOON's tabular form (never the inline/keyed-tabular/list forms the full
    spec also defines), so this decoder only needs to understand that one —
    it is not a general TOON parser. Raises `ValueError` on anything else."""
    lines = [ln for ln in text.splitlines() if ln.strip()]
    if not lines:
        return []
    header = lines[0].strip()
    m = _TOON_HEADER_RE.match(header)
    if not m:
        raise ValueError(f"not a TOON tabular header (this decoder only reads that form): {header!r}")
    n = int(m.group(1))
    field_str = m.group(2)
    fields = field_str.split(delimiter) if field_str else []
    rows: list[dict] = []
    for line in lines[1 : 1 + n]:
        cells = _toon_split_row(line.strip(), delimiter)
        rows.append(dict(zip(fields, cells)))
    return rows


# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

def _emit(obj: Any) -> None:
    print(json.dumps(obj, indent=2, ensure_ascii=False))


def _emit_rows(rows: list[dict], fmt: str) -> None:
    if fmt == "toon":
        print(encode_toon(rows))
    else:
        _emit(rows)


def _die(message: str, code: int = 1) -> None:
    sys.stderr.write(f"error: {message}\n")
    raise SystemExit(code)


# ---------------------------------------------------------------------------
# Verdict wiring — deliberately NOT imported from server.py (see module
# docstring: server.py imports the TOON encoder from here, so the reverse
# import would cycle). Same two small helpers server.py's own
# `_resolver`/`_attach_verdict` implement, over this CLI's own cache handle.
# ---------------------------------------------------------------------------

def _resolver(c: "cache_mod.RegistryCache"):
    c.ensure_fresh()
    reg = c.registry
    return (lambda code: reg.by_code.get(code)) if reg else (lambda code: None)


def _attach_verdict(c: "cache_mod.RegistryCache", entry: dict | None) -> dict | None:
    if entry is None:
        return None
    return {"entry": entry, "verdict": verdict.verdict_for_entry(entry, _resolver(c)).to_dict()}


def _row_with_verdict(c: "cache_mod.RegistryCache", row: dict) -> dict:
    """This CLI's own extension over every row-list subcommand
    (`find`/`by-root`/`by-domain`/`by-record`/`descendants`): attach a
    compact `verdict`/`usable` pair per row. The founder rule this whole
    package exists to enforce ("every equation must be looked up before it
    is used") applies to a listing surface exactly as much as to a single
    `show`/`check` — a code printed by `toledo find` should not need a
    second command before a caller can tell whether it is safe to cite.
    `neighbours`' rows are relation edges, not citable entries in their own
    right (mirrors server.py's `toledo_neighbours` docstring: "the
    'relation' members are cross-links... and carry no verdict"), so
    `cmd_neighbours` below does not call this."""
    full = c.registry.by_code.get(row.get("code")) if c.registry else None
    if full is None:
        return row
    v = verdict.verdict_for_entry(full, _resolver(c))
    return {**row, "verdict": v.verdict, "usable": v.usable}


def _rows_with_verdict(c: "cache_mod.RegistryCache", rows: list[dict]) -> list[dict]:
    c.ensure_fresh()
    return [_row_with_verdict(c, r) for r in rows]


# ---------------------------------------------------------------------------
# Subcommands — parity set (scripts/toledo's own 8 verbs + export)
# ---------------------------------------------------------------------------

def cmd_find(args: argparse.Namespace) -> None:
    c = cache_mod.get_cache()
    try:
        rows = c.search(
            args.query, root=args.root, domain=args.domain, tier=args.tier,
            status=args.status, coq_status=args.coq_status, regex=args.regex,
            limit=args.limit,
        )
    except (regex_guard.RegexQueryTooLong, regex_guard.RegexTimeout) as exc:
        # SEC-1 fix (2026-09-07): same guard as `toledo_search` over MCP —
        # `--regex` is agent/user-supplied and unbounded regex.search() over
        # unbounded registry text can hang the whole process; fail with a
        # clear CLI error instead of hanging or crashing with a traceback.
        _die(str(exc))
        return  # unreachable, _die raises; keeps type-checkers happy
    _emit_rows(_rows_with_verdict(c, rows), args.format)


def cmd_show(args: argparse.Namespace) -> None:
    c = cache_mod.get_cache()
    result = _attach_verdict(c, c.get(args.code))
    if result is None:
        _die(f"code not found: {args.code}")
    _emit(result)


def cmd_ancestry(args: argparse.Namespace) -> None:
    c = cache_mod.get_cache()
    if c.get(args.code) is None:
        _die(f"code not found: {args.code}")
    chain = c.ancestry_chain(args.code)
    print(" -> ".join(chain))


def cmd_descendants(args: argparse.Namespace) -> None:
    c = cache_mod.get_cache()
    if c.get(args.code) is None:
        _die(f"code not found: {args.code}")
    rows = c.descendants(args.code)
    _emit_rows(_rows_with_verdict(c, rows), args.format)


def cmd_neighbours(args: argparse.Namespace) -> None:
    c = cache_mod.get_cache()
    if c.get(args.code) is None:
        _die(f"code not found: {args.code}")
    rows = c.neighbours(args.code, rel_type=args.type)
    # No per-row verdict here — these are relation edges, not citable
    # entries; see _row_with_verdict's docstring.
    _emit_rows(rows, args.format)


def cmd_by_root(args: argparse.Namespace) -> None:
    c = cache_mod.get_cache()
    rows = c.by_root(args.root, limit=args.limit)
    _emit_rows(_rows_with_verdict(c, rows), args.format)


def cmd_by_domain(args: argparse.Namespace) -> None:
    c = cache_mod.get_cache()
    rows = c.by_domain(args.domain, limit=args.limit)
    _emit_rows(_rows_with_verdict(c, rows), args.format)


def cmd_by_record(args: argparse.Namespace) -> None:
    c = cache_mod.get_cache()
    rows = c.by_record(args.record_id)
    _emit_rows(_rows_with_verdict(c, rows), args.format)


def cmd_export(args: argparse.Namespace) -> None:
    """Unlike `scripts/toledo export` (which reads the generated
    `registry/TOLEDO.json`/`graph/toledo.graphml` files verbatim), `json`/
    `md` here are built fresh from the cached registry so they never lag a
    `make build` run; `graphml` has no cache-layer equivalent to rebuild
    from (it is the registry-owning lane's own generated artifact) and is
    read straight from `graph/toledo.graphml` if present, exactly as
    `scripts/toledo export --format graphml` already does."""
    c = cache_mod.get_cache()
    c.ensure_fresh()
    entries = core.sort_codes(list(c.registry.entries))
    if args.format == "json":
        _emit({"canonical": entries})
    elif args.format == "md":
        for e in entries:
            print(f"## {e['code']} — {e.get('name', '')}")
            print()
            print((e.get("statement") or {}).get("latest", ""))
            print()
    elif args.format == "graphml":
        graph_path = paths.repo_root() / "graph" / "toledo.graphml"
        if not graph_path.exists():
            _die(f"{graph_path} not found — run scripts/toledo_build.py first", code=2)
        print(graph_path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Subcommands — new, verdict-aware surface (mcp/DESIGN.md sec. 14)
# ---------------------------------------------------------------------------

def cmd_check(args: argparse.Namespace) -> None:
    """Mirrors `server.py`'s `toledo_check` tool body (see module docstring
    for why this is a deliberate, checked duplication rather than an
    import)."""
    if bool(args.formula) == bool(args.code):
        _emit({
            "verdict": "AMBIGUOUS", "usable": False,
            "reason": "pass exactly one of --formula or --code, not both and not neither.",
            "redirect": [], "candidates": [],
        })
        return
    c = cache_mod.get_cache()
    c.ensure_fresh()
    if args.code:
        entry = c.get(args.code)
        _emit(verdict.verdict_for_check(entry, [], _resolver(c)).to_dict())
        return
    if args.method == "difflib":
        # R3-1 fix (2026-09-07): mirrors server.py's toledo_check fix (see
        # its own comment for the full reasoning) — a "registered" verdict
        # from `core.check`'s bare similarity threshold used to map straight
        # to REGISTERED_CURRENT/usable=True with no check of the matched
        # entry's own `status`. Resolve the top match and delegate to the
        # same status-aware `verdict.verdict_for_entry` a code lookup goes
        # through, instead of trusting the threshold alone.
        result = core.check(c.registry, args.formula, limit=args.limit)
        if result["verdict"] == "registered":
            # R3-3 fix (2026-09-07): mirrors server.py's toledo_check fix
            # (see its own comment for the full reasoning) — `matches[0]`
            # used to be picked blindly even when two or more DIFFERENT
            # codes tied at the top similarity score. Report AMBIGUOUS
            # naming every tied code instead of resolving just the first.
            top_score = result["matches"][0]["similarity"] if result["matches"] else None
            tied_codes = sorted({
                m["code"] for m in result["matches"]
                if m.get("similarity") == top_score
            }) if top_score is not None else []
            if len(tied_codes) > 1:
                _emit({
                    "verdict": "AMBIGUOUS", "usable": False,
                    "reason": (
                        f"core.check (difflib) found {len(tied_codes)} different codes tied at "
                        f"similarity {top_score} — this statement is registered under several "
                        f"codes: {tied_codes} — escalate to a human, do not pick one."
                    ),
                    "redirect": [], "candidates": result["matches"],
                })
                return
            top_match = result["matches"][0] if result["matches"] else None
            top_code = top_match.get("code") if top_match else None
            matched_entry = c.registry.by_code.get(top_code) if top_code else None
            if matched_entry is None:
                _emit({
                    "verdict": "AMBIGUOUS", "usable": False,
                    "reason": (
                        f"core.check (difflib) reported a registered match to {top_code!r} but it "
                        "could not be re-resolved to a full entry — escalate to a human."
                    ),
                    "redirect": [], "candidates": result["matches"],
                })
                return
            v = verdict.verdict_for_entry(matched_entry, _resolver(c))
            _emit({
                "verdict": v.verdict, "usable": v.usable,
                "reason": f"core.check (difflib) best_score={result['best_score']}; {v.reason}",
                "redirect": v.redirect, "candidates": result["matches"],
            })
            return
        mapped = {
            "candidate - confirm": "CANDIDATE_MATCH",
            "not found - must register before use": "NOT_REGISTERED",
        }[result["verdict"]]
        _emit({
            "verdict": mapped, "usable": False,
            "reason": f"core.check (difflib) best_score={result['best_score']}",
            "redirect": [], "candidates": result["matches"],
        })
        return
    candidates = c.find_equivalence_candidates(args.formula, limit=args.limit)
    _emit(verdict.verdict_for_check(None, candidates, _resolver(c)).to_dict())


def cmd_status(args: argparse.Namespace) -> None:
    c = cache_mod.get_cache()
    entry = c.get(args.code)
    summary = c.status(args.code)
    if entry is None or summary is None:
        _emit(None)
        return
    v = verdict.verdict_for_entry(entry, _resolver(c))
    _emit({**summary, "verdict": v.verdict, "usable": v.usable, "verdict_reason": v.reason, "redirect": v.redirect})


def cmd_index_status(args: argparse.Namespace) -> None:
    _emit(cache_mod.get_cache().index_status())


def cmd_show_verdict_rules(args: argparse.Namespace) -> None:
    """Wraps the same introspection `mcp/DESIGN.md` sec. 8 specifies as the
    `toledo_show_verdict_rules` MCP tool. As of this build, `verdict.py`
    (owned by S2) has not yet landed the `RULES`/`_KNOWN_STATUSES` module
    data that section describes — confirmed by `getattr` below, not
    assumed. Rather than hand-typing a second copy of the rule table here
    (which is exactly the drift `mcp/DESIGN.md` sec. 8 says `RULES` exists
    to prevent), this reports that honestly instead of fabricating a table
    that is not actually the code's own decision path. See
    `tests/test_cli.py::test_show_verdict_rules_activates_once_verdict_py_exposes_rules`
    for the pinned expectation once S2 lands it."""
    rules = getattr(verdict, "RULES", None)
    known = getattr(verdict, "_KNOWN_STATUSES", None)
    values = getattr(verdict, "VERDICT_VALUES", None)
    if rules is None or known is None or values is None:
        _emit({
            "available": False,
            "reason": (
                "verdict.py does not yet expose RULES/_KNOWN_STATUSES/"
                "VERDICT_VALUES on this build (mcp/DESIGN.md sec. 8, graft "
                "A6) — pending that module's own owner; nothing here "
                "fabricates a rule table that is not the code's real "
                "decision path."
            ),
        })
        return
    _emit({"available": True, "statuses": sorted(known), "verdict_values": list(values), "rules": rules})


def cmd_proposals_list(args: argparse.Namespace) -> None:
    root = paths.repo_root()
    rows = proposals.list_proposals(status=args.status, limit=args.limit, root=root)
    _emit_rows(rows, args.format)


def cmd_proposals_show(args: argparse.Namespace) -> None:
    root = paths.repo_root()
    doc = proposals.get_proposal(args.path, root=root)
    if doc is None:
        _die(f"no proposal at path: {args.path}")
    _emit(doc)


def cmd_register_proposal(args: argparse.Namespace) -> None:
    """Reads a JSON file shaped like `mcp/DESIGN.md` sec. 6's proposal
    object — either the whole `{"proposal": {...}, ...}` document a prior
    `register-proposal`/`toledo_register_proposal` call produced, or just
    the bare `fields` object it wraps — and calls the same
    `core.register_proposal` the MCP tool does, then records the same
    `PENDING` ledger row `server.py`'s `toledo_register_proposal` does."""
    src = pathlib.Path(args.from_json)
    if not src.exists():
        _die(f"no such file: {src}")
    try:
        raw = json.loads(src.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        _die(f"{src} is not valid JSON: {exc}")
        return  # unreachable, _die raises; keeps type-checkers happy
    fields = raw.get("proposal", raw) if isinstance(raw, dict) else raw
    root = paths.repo_root()
    result = core.register_proposal(fields, repo_root=root)
    proposals.record_submitted(result["path"], result["slug"], result["submitted_at"], root=root)
    _emit(result)


# ---------------------------------------------------------------------------
# argparse wiring
# ---------------------------------------------------------------------------

def _add_format(p: argparse.ArgumentParser) -> None:
    p.add_argument("--format", choices=["json", "toon"], default="json",
                    help="json (default) or toon (mcp/DESIGN.md sec. 7 — uniform "
                         "row lists only; see this workspace's toon-format skill)")


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="toledo",
        description=(
            "toledo_mcp's own CLI over the cached/indexed Toledo registry. "
            "Founder rule (2026-09-07): every equation must be looked up here "
            "before it is used; never use a result whose verdict is not usable."
        ),
    )
    sub = ap.add_subparsers(dest="command", required=True)

    p = sub.add_parser("find", help="search code/aliases/name/statement, optionally filtered")
    p.add_argument("query", nargs="?", default="")
    p.add_argument("--root", default=None)
    p.add_argument("--domain", default=None)
    p.add_argument("--tier", default=None)
    p.add_argument("--status", default=None)
    p.add_argument("--coq-status", dest="coq_status", default=None)
    p.add_argument("--regex", action="store_true")
    p.add_argument("--limit", type=int, default=20,
                    help="0 or omitted = default of 20 (never unlimited); negative is an error")
    _add_format(p)
    p.set_defaults(func=cmd_find)

    p = sub.add_parser("show", help="one code's full entry + verdict")
    p.add_argument("code")
    p.set_defaults(func=cmd_show)

    p = sub.add_parser("ancestry", help="root-first chain from the Genesis root to a code")
    p.add_argument("code")
    p.set_defaults(func=cmd_ancestry)

    p = sub.add_parser("descendants", help="every code reachable via children[] edges")
    p.add_argument("code")
    _add_format(p)
    p.set_defaults(func=cmd_descendants)

    p = sub.add_parser("neighbours", help="direct parent/child/relation neighbours (+ reverse relations)")
    p.add_argument("code")
    p.add_argument("--type", default=None)
    _add_format(p)
    p.set_defaults(func=cmd_neighbours)

    p = sub.add_parser("by-root", help="every code under a given root")
    p.add_argument("root")
    p.add_argument("--limit", type=int, default=None,
                    help="0 or omitted = uncapped (every matching entry); negative is an error")
    _add_format(p)
    p.set_defaults(func=cmd_by_root)

    p = sub.add_parser("by-domain", help="every code in a given domain letter")
    p.add_argument("domain")
    p.add_argument("--limit", type=int, default=None,
                    help="0 or omitted = uncapped (every matching entry); negative is an error")
    _add_format(p)
    p.set_defaults(func=cmd_by_domain)

    p = sub.add_parser("by-record", help="every code occurring in a given Zenodo record id/doi")
    p.add_argument("record_id")
    _add_format(p)
    p.set_defaults(func=cmd_by_record)

    p = sub.add_parser("export", help="export the cached registry (json/md), or graph/toledo.graphml verbatim")
    p.add_argument("--format", choices=["json", "graphml", "md"], required=True)
    p.set_defaults(func=cmd_export)

    p = sub.add_parser("check", help="FOUNDER RULE: verdict for a formula or an exact code")
    p.add_argument("--formula", default=None)
    p.add_argument("--code", default=None)
    p.add_argument("--limit", type=int, default=5,
                    help="0 or omitted = default of 5 (never empty); negative is an error")
    p.add_argument("--method", choices=["phi", "difflib"], default="phi")
    p.set_defaults(func=cmd_check)

    p = sub.add_parser("status", help="compact tier/status/coq_status/verdict readout for one code")
    p.add_argument("code")
    p.set_defaults(func=cmd_status)

    p = sub.add_parser("index-status", help="this build's index health/versioning readout")
    p.set_defaults(func=cmd_index_status)

    p = sub.add_parser("show-verdict-rules", help="introspect the verdict decision table (verdict.py)")
    p.set_defaults(func=cmd_show_verdict_rules)

    p_proposals = sub.add_parser("proposals", help="submitted registration proposals")
    proposals_sub = p_proposals.add_subparsers(dest="proposals_command", required=True)

    p = proposals_sub.add_parser("list", help="list proposals, newest first")
    p.add_argument("--status", default=None, choices=["PENDING", "ACCEPTED", "REJECTED", "SUPERSEDED"])
    p.add_argument("--limit", type=int, default=50,
                    help="0 or omitted = default of 50 (never unlimited); negative is an error")
    _add_format(p)
    p.set_defaults(func=cmd_proposals_list)

    p = proposals_sub.add_parser("show", help="one proposal's full document + lifecycle status")
    p.add_argument("path")
    p.set_defaults(func=cmd_proposals_show)

    p = sub.add_parser("register-proposal", help="FOUNDER RULE: submit a proposal for an unregistered equation")
    p.add_argument("--from-json", dest="from_json", required=True,
                    help="a JSON file shaped like mcp/DESIGN.md sec. 6's proposal object (or its bare fields)")
    p.set_defaults(func=cmd_register_proposal)

    return ap


def main(argv: list[str] | None = None) -> int:
    ap = build_parser()
    args = ap.parse_args(argv)
    args.func(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
