From RDL Require Import CMC_PhysicsClass_Instances.
Print Assumptions Retention_Lemma_certified.
Print Assumptions Finite_Speed_Lemma_certified.
Print Assumptions Closure_Exhaustion_Lemma_certified.
Print Assumptions certified_physical_readout_has_nonzero_closure.
Print Assumptions certified_physical_readout_blocks_refuter.
Print Assumptions cattaneo_telegraph_closure_witness.
Print Assumptions cattaneo_telegraph_blocks_refuter.
Print Assumptions kinetic_transport_closure_witness.
Print Assumptions kinetic_transport_blocks_refuter.
Print Assumptions flux_limited_diffusion_closure_witness.
Print Assumptions flux_limited_diffusion_blocks_refuter.
Print Assumptions wave_bounded_propagator_closure_witness.
Print Assumptions wave_bounded_propagator_blocks_refuter.
Print Assumptions fourier_heat_singular_memoryless_face_not_finite_speed_target.
Print Assumptions fourier_heat_singular_memoryless_face_not_refuter.
