From RDL Require Import RD.
Print Assumptions RD3_succ_ne_zero.
Print Assumptions RD4_succ_inj.
Print Assumptions add_zero.
Print Assumptions add_succ.
Print Assumptions zero_add.
Print Assumptions succ_add.
Print Assumptions add_assoc.
Print Assumptions add_comm.
Print Assumptions mul_zero.
Print Assumptions mul_succ.
Print Assumptions zero_mul.
Print Assumptions mul_add.
Print Assumptions iso_to_of.
Print Assumptions iso_of_to.
Print Assumptions toNat_inj.
Print Assumptions toNat_add.
Print Assumptions toNat_mul.
Print Assumptions mul_comm.
Print Assumptions mul_assoc.
Print Assumptions mul_one.
Print Assumptions one_mul.
Print Assumptions add_mul.
Print Assumptions le_refl.
Print Assumptions le_trans.
Print Assumptions le_toNat.
Print Assumptions toNat_le.
Print Assumptions le_antisym.
Print Assumptions le_total.
Print Assumptions add_cancel_r.
Print Assumptions lt_toNat.
Print Assumptions lt_irrefl.
Print Assumptions lt_trans.
Print Assumptions lt_trichotomy.
Print Assumptions lt_wf.
Print Assumptions strong_induction.
Print Assumptions eval_hom.
Print Assumptions eqn_transfer.
Print Assumptions evN_ext.
Print Assumptions evD_evN.
Print Assumptions sat_transfer.
Print Assumptions sentence_transfer.
Print Assumptions evD_ext.
Print Assumptions evD_shift.
Print Assumptions evD_subst.
Print Assumptions satD_ext.
Print Assumptions satD_subst.
Print Assumptions soundness.
Print Assumptions consistency.
Print Assumptions prov_sound_N.
Print Assumptions D_validates_induction.
Print Assumptions D_models_PA.
Print Assumptions PA_closed.
Print Assumptions Con_PA.
Print Assumptions PA_true_in_N.
Print Assumptions emb_surj.
Print Assumptions emb_inj.
Print Assumptions categoricity.
Print Assumptions dist_self.
Print Assumptions dist_eq0.
Print Assumptions dist_pos.
Print Assumptions dist_sym.
Print Assumptions dist_tri.
Print Assumptions Betw_id.
Print Assumptions Betw_sym.
Print Assumptions Betw_refl_l.
Print Assumptions dist2_self.
Print Assumptions dist2_eq0.
Print Assumptions dist2_sym.
Print Assumptions dist2_tri.
Print Assumptions zeq_zval.
Print Assumptions zval_z0.
Print Assumptions zval_z1.
Print Assumptions zval_add.
Print Assumptions zval_neg.
Print Assumptions zval_mul.
Print Assumptions zeq_refl.
Print Assumptions zeq_sym.
Print Assumptions zeq_trans.
Print Assumptions zadd_cong.
Print Assumptions zneg_cong.
Print Assumptions zmul_cong.
Print Assumptions zadd_comm.
Print Assumptions zadd_assoc.
Print Assumptions zadd_0_l.
Print Assumptions zadd_neg.
Print Assumptions zmul_comm.
Print Assumptions zmul_assoc.
Print Assumptions zmul_1_l.
Print Assumptions zmul_distrib_l.
Print Assumptions Sum_zero.
Print Assumptions Sum_succ.
Print Assumptions zval_sub.
Print Assumptions zval_Delta.
Print Assumptions FTC_Z.
Print Assumptions FTC.
Print Assumptions FTC_inverse.
Print Assumptions Leibniz.
Print Assumptions injZ_neq0.
Print Assumptions qok_add.
Print Assumptions qok_mul.
Print Assumptions qok_neg.
Print Assumptions qok_inv.
Print Assumptions qval_q0.
Print Assumptions qval_q1.
Print Assumptions qval_add.
Print Assumptions qval_mul.
Print Assumptions qval_neg.
Print Assumptions qeq_refl.
Print Assumptions qeq_sym.
Print Assumptions qeq_trans.
Print Assumptions qadd_comm.
Print Assumptions qadd_assoc.
Print Assumptions qadd_0_l.
Print Assumptions qadd_neg.
Print Assumptions qmul_comm.
Print Assumptions qmul_assoc.
Print Assumptions qmul_1_l.
Print Assumptions qmul_distrib_l.
Print Assumptions qmul_inv.
Print Assumptions two_halves.
Print Assumptions two_halves'.
Print Assumptions inv_mono.
Print Assumptions Qle_lim.
Print Assumptions Qle_lim2.
Print Assumptions Req_refl.
Print Assumptions Req_sym.
Print Assumptions Req_trans.
Print Assumptions Radd_comm.
Print Assumptions Radd_0_l.
Print Assumptions Radd_opp.
Print Assumptions Qarch1.
Print Assumptions Qle_limc.
Print Assumptions Rle_refl.
Print Assumptions Rle_trans.
Print Assumptions close_Req.
Print Assumptions Rle_antisym.
Print Assumptions inj_Q_le.
Print Assumptions Radd_le_mono_r.
Print Assumptions Rlt_irrefl.
Print Assumptions scaleN.
Print Assumptions Rbound.
Print Assumptions Rmul_comm.
Print Assumptions Rmul_1_l.
Print Assumptions IB_pos.
Print Assumptions prod_reg.
Print Assumptions prod_mix.
Print Assumptions IB_scale.
Print Assumptions Rmul_wd.
Print Assumptions inv_idx_le.
Print Assumptions prod_reg2.
Print Assumptions prod_reg2_k.
Print Assumptions Rmul_distrib_l.
Print Assumptions kle1.
Print Assumptions kle3.
Print Assumptions pair_bound.
Print Assumptions tri_bound.
Print Assumptions prod_reg3_k.
Print Assumptions Rmul_assoc.
Print Assumptions frac_split.
Print Assumptions Qarch_c.
Print Assumptions Rlt_le_weak.
Print Assumptions Rlt_trans.
Print Assumptions Rlt_cotrans.
Print Assumptions Rle_max_l.
Print Assumptions Rle_max_r.
Print Assumptions Rmax_lub.
Print Assumptions Rmin_le_l.
Print Assumptions Rmin_le_r.
Print Assumptions Rmin_glb.
Print Assumptions Rconv_const.
Print Assumptions Rlimit_unique.
Print Assumptions Rconv_recip.
Print Assumptions Rdist_self.
Print Assumptions Rdist_sym.
Print Assumptions Rdist_nonneg.
Print Assumptions Rdist_triangle.
Print Assumptions Rabs_Lipschitz.
Print Assumptions Ropp_isometry.
Print Assumptions Radd_Lipschitz.
Print Assumptions Rcontinuous_id.
Print Assumptions Rcontinuous_Rabs.
Print Assumptions soundnessC.
Print Assumptions consistencyC.
Print Assumptions Con_PA_classical.
