From RDL Require Import RDL_PhaseSound.
Print Assumptions dual_involutive.
Print Assumptions inc_refl.
Print Assumptions inc_trans.
Print Assumptions equiv_refl.
Print Assumptions equiv_sym.
Print Assumptions equiv_trans.
Print Assumptions orth_antitone.
Print Assumptions inc_orth_orth.
Print Assumptions orth3.
Print Assumptions equiv_orth.
Print Assumptions clo_mono.
Print Assumptions equiv_clo.
Print Assumptions orth_fact.
Print Assumptions fact_orthorth.
Print Assumptions fact_equiv.
Print Assumptions pmul_comm.
Print Assumptions pmul_mono.
Print Assumptions pmul_equiv.
Print Assumptions pmul_assoc.
Print Assumptions pmul_unit_l.
Print Assumptions pmul_unit_r.
Print Assumptions pmul_swap.
Print Assumptions pmul_orth_adj.
Print Assumptions orth_union_split.
Print Assumptions union_equiv.
Print Assumptions with_fact.
Print Assumptions withF_equiv.
Print Assumptions Den_app.
Print Assumptions Den_perm.
Print Assumptions sem_fact.
Print Assumptions sem_dual.
Print Assumptions peel.
Print Assumptions soundness.
Print Assumptions valid_pair.
Print Assumptions valid_AA.
Print Assumptions contraction_needs_idem.
Print Assumptions u_comm.
Print Assumptions u_assoc.
Print Assumptions u_unit.
Print Assumptions u_Vfact.
Print Assumptions consistent.
Print Assumptions n_comm.
Print Assumptions n_assoc.
Print Assumptions n_unit.
Print Assumptions geq1_fact.
Print Assumptions no_contraction.
