From RDL Require Import RDL_All.
Print Assumptions Sequent.cons_des.
Print Assumptions CutElim.cons_des.
Print Assumptions Sequent.sound.
Print Assumptions Sequent.non_explosion.
Print Assumptions Sequent.classical_explosion.
Print Assumptions Sequent.contradiction_is_obstruction.
Print Assumptions CutElim.perm_adm.
Print Assumptions CutElim.weak_adm.
Print Assumptions CutElim.cut_adm.
Print Assumptions CutElim.cut_elim.
Print Assumptions PhaseSetoid.cut_elim.
Print Assumptions CutElim.sound_cf.
Print Assumptions CutElim.cut_free_non_explosion.
Print Assumptions FOL.ttff_ext.
Print Assumptions FOL.rename_sound.
Print Assumptions FOL.inst_sound.
Print Assumptions FOL.shift_ctx.
Print Assumptions FOL.soundF.
Print Assumptions Linear.gsum_nil.
Print Assumptions Linear.gsum_cons.
Print Assumptions Linear.gsum_app.
Print Assumptions Linear.gsum_perm.
Print Assumptions Linear.Lin_grading.
Print Assumptions Linear.weakening_unsound.
Print Assumptions Linear.contraction_unsound.
Print Assumptions Linear.bang_derelict.
Print Assumptions Linear.bang_weak.
Print Assumptions Linear.bang_dup.
Print Assumptions Modal.K_valid.
Print Assumptions Modal.nec.
Print Assumptions Modal.T_valid.
Print Assumptions Modal.Four_valid.
Print Assumptions Modal.s4_sound.
Print Assumptions Graph.Qsq_nonneg.
Print Assumptions Gamma.Qsq_nonneg.
Print Assumptions Graph.Qsq_eq0.
Print Assumptions Graph.Qmult_pos_eq0.
Print Assumptions Graph.sumV_nil.
Print Assumptions Graph.sumV_cons.
Print Assumptions Graph.sumV_nonneg.
Print Assumptions Graph.sumV_eq0.
Print Assumptions Graph.sumV_zero_each.
Print Assumptions Graph.energy_nonneg.
Print Assumptions Gamma.energy_nonneg.
Print Assumptions Graph.energy_const.
Print Assumptions Graph.reach_inL.
Print Assumptions Graph.energy_zero_edge.
Print Assumptions Graph.reach_eq.
Print Assumptions Graph.kernel_connected.
Print Assumptions Readout.record_ne_latent.
Print Assumptions Readout.readout_loses.
Print Assumptions Readout.resolution_internal_zero.
Print Assumptions Readout.resolution_refine.
Print Assumptions RuleSound.resolution_sound.
Print Assumptions RuleSound.resolution_creates_validity.
Print Assumptions RuleSound.record_sound.
Print Assumptions RuleSound.record_not_factive.
Print Assumptions Rules.R_dist.
Print Assumptions RetCenter.R_dist.
Print Assumptions Rules.R_nec.
Print Assumptions RetCenter.R_nec.
Print Assumptions Rules.R_not_factive.
Print Assumptions Rules.resolution_rule.
Print Assumptions Phase.inc_refl.
Print Assumptions PhaseSound.inc_refl.
Print Assumptions PhaseSetoid.inc_refl.
Print Assumptions Phase.inc_trans.
Print Assumptions PhaseSound.inc_trans.
Print Assumptions PhaseSetoid.inc_trans.
Print Assumptions Phase.orth_antitone.
Print Assumptions PhaseSound.orth_antitone.
Print Assumptions PhaseSetoid.orth_antitone.
Print Assumptions RetCenter.orth_antitone.
Print Assumptions Phase.inc_orth_orth.
Print Assumptions PhaseSound.inc_orth_orth.
Print Assumptions PhaseSetoid.inc_orth_orth.
Print Assumptions Phase.orth3.
Print Assumptions PhaseSound.orth3.
Print Assumptions PhaseSetoid.orth3.
Print Assumptions Phase.equiv_orth.
Print Assumptions PhaseSound.equiv_orth.
Print Assumptions PhaseSetoid.equiv_orth.
Print Assumptions Phase.clo_mono.
Print Assumptions PhaseSound.clo_mono.
Print Assumptions PhaseSetoid.clo_mono.
Print Assumptions Phase.equiv_clo.
Print Assumptions PhaseSound.equiv_clo.
Print Assumptions PhaseSetoid.equiv_clo.
Print Assumptions Phase.orth_fact.
Print Assumptions PhaseSound.orth_fact.
Print Assumptions PhaseSetoid.orth_fact.
Print Assumptions Phase.fact_orthorth.
Print Assumptions PhaseSound.fact_orthorth.
Print Assumptions PhaseSetoid.fact_orthorth.
Print Assumptions Phase.dual_fact.
Print Assumptions Phase.dual_invol.
Print Assumptions Phase.tens_fact.
Print Assumptions Phase.tens_comm.
Print Assumptions Phase.one_fact.
Print Assumptions Phase.bot_fact.
Print Assumptions Phase.with_fact.
Print Assumptions PhaseSound.with_fact.
Print Assumptions PhaseSetoid.with_fact.
Print Assumptions Phase.with_meet_l.
Print Assumptions Phase.with_meet_r.
Print Assumptions Phase.plus_fact.
Print Assumptions Phase.plus_join_l.
Print Assumptions Phase.plus_join_r.
Print Assumptions Involution.dual_involutive.
Print Assumptions PhaseSound.dual_involutive.
Print Assumptions Involution.id_expand.
Print Assumptions PhaseSound.equiv_refl.
Print Assumptions PhaseSetoid.equiv_refl.
Print Assumptions PhaseSound.equiv_sym.
Print Assumptions PhaseSetoid.equiv_sym.
Print Assumptions PhaseSound.equiv_trans.
Print Assumptions PhaseSetoid.equiv_trans.
Print Assumptions PhaseSound.fact_equiv.
Print Assumptions PhaseSetoid.fact_equiv.
Print Assumptions PhaseSound.pmul_comm.
Print Assumptions PhaseSetoid.pmul_comm.
Print Assumptions PhaseSound.pmul_mono.
Print Assumptions PhaseSetoid.pmul_mono.
Print Assumptions PhaseSound.pmul_equiv.
Print Assumptions PhaseSetoid.pmul_equiv.
Print Assumptions PhaseSound.pmul_assoc.
Print Assumptions PhaseSetoid.pmul_assoc.
Print Assumptions PhaseSound.pmul_unit_l.
Print Assumptions PhaseSetoid.pmul_unit_l.
Print Assumptions PhaseSound.pmul_unit_r.
Print Assumptions PhaseSetoid.pmul_unit_r.
Print Assumptions PhaseSound.pmul_swap.
Print Assumptions PhaseSetoid.pmul_swap.
Print Assumptions PhaseSound.pmul_orth_adj.
Print Assumptions PhaseSetoid.pmul_orth_adj.
Print Assumptions PhaseSound.orth_union_split.
Print Assumptions PhaseSetoid.orth_union_split.
Print Assumptions PhaseSound.union_equiv.
Print Assumptions PhaseSetoid.union_equiv.
Print Assumptions PhaseSound.withF_equiv.
Print Assumptions PhaseSetoid.withF_equiv.
Print Assumptions PhaseSound.Den_app.
Print Assumptions PhaseSetoid.Den_app.
Print Assumptions PhaseSound.Den_perm.
Print Assumptions PhaseSetoid.Den_perm.
Print Assumptions PhaseSound.sem_fact.
Print Assumptions PhaseSetoid.sem_fact.
Print Assumptions PhaseSound.sem_dual.
Print Assumptions PhaseSetoid.sem_dual.
Print Assumptions PhaseSound.peel.
Print Assumptions PhaseSetoid.peel.
Print Assumptions PhaseSound.soundness.
Print Assumptions PhaseSetoid.soundness.
Print Assumptions PhaseSound.valid_pair.
Print Assumptions PhaseSound.valid_AA.
Print Assumptions PhaseSound.contraction_needs_idem.
Print Assumptions PhaseSound.valid_AB.
Print Assumptions PhaseSound.additive_needs_collapse.
Print Assumptions PhaseSound.u_comm.
Print Assumptions PhaseSound.u_assoc.
Print Assumptions PhaseSound.u_unit.
Print Assumptions PhaseSound.u_Vfact.
Print Assumptions PhaseSound.consistent.
Print Assumptions PhaseSetoid.consistent.
Print Assumptions PhaseSound.n_comm.
Print Assumptions PhaseSound.n_assoc.
Print Assumptions PhaseSound.n_unit.
Print Assumptions PhaseSound.geq1_fact.
Print Assumptions PhaseSound.no_contraction.
Print Assumptions PhaseSound.no_additive.
Print Assumptions PhaseSound.geq1_fact3.
Print Assumptions PhaseSound.geq2_fact3.
Print Assumptions PhaseSound.v3_Vfact.
Print Assumptions PhaseSound.atoms_distinct.
Print Assumptions PhaseSound.no_additive_distinct.
Print Assumptions PhaseSound.Pcf_Prov.
Print Assumptions PhaseSetoid.Pcf_Prov.
Print Assumptions PhaseSound.cut_free_consistent.
Print Assumptions PhaseSound.no_contraction_cf.
Print Assumptions PhaseSound.no_additive_cf.
Print Assumptions PhaseSound.id_cf.
Print Assumptions PhaseSound.soundness_all.
Print Assumptions PhaseSound.cut_elim_from_cf_completeness.
Print Assumptions PhaseSound.Pcf_pole_proper.
Print Assumptions ContextSetoid.context_comm_no_funext.
Print Assumptions PhaseSetoid.orth_cl.
Print Assumptions PhaseSetoid.pmul_cl.
Print Assumptions PhaseSetoid.unitSet_cl.
Print Assumptions PhaseSetoid.Den_cl.
Print Assumptions PhaseSetoid.soundness_strict.
Print Assumptions PhaseSetoid.context_phase_soundness.
Print Assumptions PhaseSetoid.Pcf_proper.
Print Assumptions PhaseSetoid.cf_snoc.
Print Assumptions PhaseSetoid.Sv_fact.
Print Assumptions PhaseSetoid.orth_app.
Print Assumptions PhaseSetoid.orth_intro.
Print Assumptions PhaseSetoid.reflect.
Print Assumptions PhaseSetoid.G_in_DenG.
Print Assumptions PhaseSetoid.cut_admissible.
Print Assumptions PhaseSetoid.Pcf_len.
Print Assumptions PhaseSetoid.cf_consistent.
Print Assumptions RetCenter.orth_expand.
Print Assumptions RetCenter.orth_triple.
Print Assumptions RetCenter.readout_invariant.
Print Assumptions RetCenter.perm_equiv.
Print Assumptions RetCenter.app_perm_proper.
Print Assumptions RetCenter.app_perm_comm.
Print Assumptions RetCenter.app_perm_assoc.
Print Assumptions RetCenter.app_perm_unit.
Print Assumptions RetCenter.nat_le_preorder.
Print Assumptions RetCenter.pole_perm.
Print Assumptions RetCenter.length_perm_inv.
Print Assumptions RetCenter.canonical_readout_invariant.
Print Assumptions RetCenter.canonical_record_lossy.
Print Assumptions RetCenter.box_mono.
Print Assumptions RetCenter.box_K.
Print Assumptions RetCenter.box_nec.
Print Assumptions RetCenter.box_top.
Print Assumptions RetCenter.box_and.
Print Assumptions RetCenter.box_T.
Print Assumptions RetCenter.box_4.
Print Assumptions RetCenter.R_fiber_factive.
Print Assumptions RetCenter.gauge_refines_record.
Print Assumptions RetCenter.R_not_factive_canonical.
Print Assumptions StarRig.adj_is_involution.
Print Assumptions StarRig.sum_mul_lr.
Print Assumptions StarRig.term_eq.
Print Assumptions StarRig.kraus_completeness.
Print Assumptions Gamma.Qplus_nonneg.
Print Assumptions Gamma.Qmul_nonneg.
Print Assumptions Gamma.energy_edge_gauge.
Print Assumptions Gamma.energy_zero_edges.
Print Assumptions Gamma.laplacian_stencil.
Print Assumptions Gamma.secondDiff_quadratic.
Print Assumptions Gamma.secondDiff_readout_invariant.
