From RDL Require Import URCF_RD_All.
Print Assumptions Sequent.cons_des.
Print Assumptions CutElim.cons_des.
Print Assumptions Sequent.sound.
Print Assumptions Sequent.non_explosion.
Print Assumptions Sequent.classical_explosion.
Print Assumptions Sequent.contradiction_is_obstruction.
Print Assumptions CutElim.perm_adm.
Print Assumptions CutElim.weak_adm.
Print Assumptions CutElim.cut_adm.
Print Assumptions CutElim.cut_elim.
Print Assumptions PhaseSetoid.cut_elim.
Print Assumptions CutElim.sound_cf.
Print Assumptions CutElim.cut_free_non_explosion.
Print Assumptions FOL.ttff_ext.
Print Assumptions FOL.rename_sound.
Print Assumptions FOL.inst_sound.
Print Assumptions FOL.shift_ctx.
Print Assumptions FOL.soundF.
Print Assumptions Linear.gsum_nil.
Print Assumptions Linear.gsum_cons.
Print Assumptions Linear.gsum_app.
Print Assumptions Linear.gsum_perm.
Print Assumptions Linear.Lin_grading.
Print Assumptions Linear.weakening_unsound.
Print Assumptions Linear.contraction_unsound.
Print Assumptions Linear.bang_derelict.
Print Assumptions Linear.bang_weak.
Print Assumptions Linear.bang_dup.
Print Assumptions Modal.K_valid.
Print Assumptions Modal.nec.
Print Assumptions Modal.T_valid.
Print Assumptions Modal.Four_valid.
Print Assumptions Modal.s4_sound.
Print Assumptions Graph.Qsq_nonneg.
Print Assumptions Gamma.Qsq_nonneg.
Print Assumptions Graph.Qsq_eq0.
Print Assumptions Graph.Qmult_pos_eq0.
Print Assumptions Graph.sumV_nil.
Print Assumptions Graph.sumV_cons.
Print Assumptions Graph.sumV_nonneg.
Print Assumptions Graph.sumV_eq0.
Print Assumptions Graph.sumV_zero_each.
Print Assumptions Graph.energy_nonneg.
Print Assumptions Gamma.energy_nonneg.
Print Assumptions Graph.energy_const.
Print Assumptions Graph.reach_inL.
Print Assumptions Graph.energy_zero_edge.
Print Assumptions Graph.reach_eq.
Print Assumptions Graph.kernel_connected.
Print Assumptions Readout.record_ne_latent.
Print Assumptions Readout.readout_loses.
Print Assumptions Readout.resolution_internal_zero.
Print Assumptions Readout.resolution_refine.
Print Assumptions RuleSound.resolution_sound.
Print Assumptions RuleSound.resolution_creates_validity.
Print Assumptions RuleSound.record_sound.
Print Assumptions RuleSound.record_not_factive.
Print Assumptions Rules.R_dist.
Print Assumptions RetCenter.R_dist.
Print Assumptions Rules.R_nec.
Print Assumptions RetCenter.R_nec.
Print Assumptions Rules.R_not_factive.
Print Assumptions Rules.resolution_rule.
Print Assumptions Phase.inc_refl.
Print Assumptions PhaseSound.inc_refl.
Print Assumptions PhaseSetoid.inc_refl.
Print Assumptions Phase.inc_trans.
Print Assumptions PhaseSound.inc_trans.
Print Assumptions PhaseSetoid.inc_trans.
Print Assumptions Phase.orth_antitone.
Print Assumptions PhaseSound.orth_antitone.
Print Assumptions PhaseSetoid.orth_antitone.
Print Assumptions RetCenter.orth_antitone.
Print Assumptions Phase.inc_orth_orth.
Print Assumptions PhaseSound.inc_orth_orth.
Print Assumptions PhaseSetoid.inc_orth_orth.
Print Assumptions Phase.orth3.
Print Assumptions PhaseSound.orth3.
Print Assumptions PhaseSetoid.orth3.
Print Assumptions Phase.equiv_orth.
Print Assumptions PhaseSound.equiv_orth.
Print Assumptions PhaseSetoid.equiv_orth.
Print Assumptions Phase.clo_mono.
Print Assumptions PhaseSound.clo_mono.
Print Assumptions PhaseSetoid.clo_mono.
Print Assumptions Phase.equiv_clo.
Print Assumptions PhaseSound.equiv_clo.
Print Assumptions PhaseSetoid.equiv_clo.
Print Assumptions Phase.orth_fact.
Print Assumptions PhaseSound.orth_fact.
Print Assumptions PhaseSetoid.orth_fact.
Print Assumptions Phase.fact_orthorth.
Print Assumptions PhaseSound.fact_orthorth.
Print Assumptions PhaseSetoid.fact_orthorth.
Print Assumptions Phase.dual_fact.
Print Assumptions Phase.dual_invol.
Print Assumptions Phase.tens_fact.
Print Assumptions Phase.tens_comm.
Print Assumptions Phase.one_fact.
Print Assumptions Phase.bot_fact.
Print Assumptions Phase.with_fact.
Print Assumptions PhaseSound.with_fact.
Print Assumptions PhaseSetoid.with_fact.
Print Assumptions Phase.with_meet_l.
Print Assumptions Phase.with_meet_r.
Print Assumptions Phase.plus_fact.
Print Assumptions Phase.plus_join_l.
Print Assumptions Phase.plus_join_r.
Print Assumptions Involution.dual_involutive.
Print Assumptions PhaseSound.dual_involutive.
Print Assumptions Involution.id_expand.
Print Assumptions PhaseSound.equiv_refl.
Print Assumptions PhaseSetoid.equiv_refl.
Print Assumptions PhaseSound.equiv_sym.
Print Assumptions PhaseSetoid.equiv_sym.
Print Assumptions PhaseSound.equiv_trans.
Print Assumptions PhaseSetoid.equiv_trans.
Print Assumptions PhaseSound.fact_equiv.
Print Assumptions PhaseSetoid.fact_equiv.
Print Assumptions PhaseSound.pmul_comm.
Print Assumptions PhaseSetoid.pmul_comm.
Print Assumptions PhaseSound.pmul_mono.
Print Assumptions PhaseSetoid.pmul_mono.
Print Assumptions PhaseSound.pmul_equiv.
Print Assumptions PhaseSetoid.pmul_equiv.
Print Assumptions PhaseSound.pmul_assoc.
Print Assumptions PhaseSetoid.pmul_assoc.
Print Assumptions PhaseSound.pmul_unit_l.
Print Assumptions PhaseSetoid.pmul_unit_l.
Print Assumptions PhaseSound.pmul_unit_r.
Print Assumptions PhaseSetoid.pmul_unit_r.
Print Assumptions PhaseSound.pmul_swap.
Print Assumptions PhaseSetoid.pmul_swap.
Print Assumptions PhaseSound.pmul_orth_adj.
Print Assumptions PhaseSetoid.pmul_orth_adj.
Print Assumptions PhaseSound.orth_union_split.
Print Assumptions PhaseSetoid.orth_union_split.
Print Assumptions PhaseSound.union_equiv.
Print Assumptions PhaseSetoid.union_equiv.
Print Assumptions PhaseSound.withF_equiv.
Print Assumptions PhaseSetoid.withF_equiv.
Print Assumptions PhaseSound.Den_app.
Print Assumptions PhaseSetoid.Den_app.
Print Assumptions PhaseSound.Den_perm.
Print Assumptions PhaseSetoid.Den_perm.
Print Assumptions PhaseSound.sem_fact.
Print Assumptions PhaseSetoid.sem_fact.
Print Assumptions PhaseSound.sem_dual.
Print Assumptions PhaseSetoid.sem_dual.
Print Assumptions PhaseSound.peel.
Print Assumptions PhaseSetoid.peel.
Print Assumptions PhaseSound.soundness.
Print Assumptions PhaseSetoid.soundness.
Print Assumptions RD.soundness.
Print Assumptions PhaseSound.valid_pair.
Print Assumptions PhaseSound.valid_AA.
Print Assumptions PhaseSound.contraction_needs_idem.
Print Assumptions PhaseSound.valid_AB.
Print Assumptions PhaseSound.additive_needs_collapse.
Print Assumptions PhaseSound.u_comm.
Print Assumptions PhaseSound.u_assoc.
Print Assumptions PhaseSound.u_unit.
Print Assumptions PhaseSound.u_Vfact.
Print Assumptions PhaseSound.consistent.
Print Assumptions PhaseSetoid.consistent.
Print Assumptions PhaseSound.n_comm.
Print Assumptions PhaseSound.n_assoc.
Print Assumptions PhaseSound.n_unit.
Print Assumptions PhaseSound.geq1_fact.
Print Assumptions PhaseSound.no_contraction.
Print Assumptions PhaseSound.no_additive.
Print Assumptions PhaseSound.geq1_fact3.
Print Assumptions PhaseSound.geq2_fact3.
Print Assumptions PhaseSound.v3_Vfact.
Print Assumptions PhaseSound.atoms_distinct.
Print Assumptions PhaseSound.no_additive_distinct.
Print Assumptions PhaseSound.Pcf_Prov.
Print Assumptions PhaseSetoid.Pcf_Prov.
Print Assumptions PhaseSound.cut_free_consistent.
Print Assumptions PhaseSound.no_contraction_cf.
Print Assumptions PhaseSound.no_additive_cf.
Print Assumptions PhaseSound.id_cf.
Print Assumptions PhaseSound.soundness_all.
Print Assumptions PhaseSound.cut_elim_from_cf_completeness.
Print Assumptions PhaseSound.Pcf_pole_proper.
Print Assumptions ContextSetoid.context_comm_no_funext.
Print Assumptions PhaseSetoid.orth_cl.
Print Assumptions PhaseSetoid.pmul_cl.
Print Assumptions PhaseSetoid.unitSet_cl.
Print Assumptions PhaseSetoid.Den_cl.
Print Assumptions PhaseSetoid.soundness_strict.
Print Assumptions PhaseSetoid.context_phase_soundness.
Print Assumptions PhaseSetoid.Pcf_proper.
Print Assumptions PhaseSetoid.cf_snoc.
Print Assumptions PhaseSetoid.Sv_fact.
Print Assumptions PhaseSetoid.orth_app.
Print Assumptions PhaseSetoid.orth_intro.
Print Assumptions PhaseSetoid.reflect.
Print Assumptions PhaseSetoid.G_in_DenG.
Print Assumptions PhaseSetoid.cut_admissible.
Print Assumptions PhaseSetoid.Pcf_len.
Print Assumptions PhaseSetoid.cf_consistent.
Print Assumptions RD.RD3_succ_ne_zero.
Print Assumptions RD.RD4_succ_inj.
Print Assumptions RD.add_zero.
Print Assumptions RD.add_succ.
Print Assumptions RD.zero_add.
Print Assumptions RD.succ_add.
Print Assumptions RD.add_assoc.
Print Assumptions RD.add_comm.
Print Assumptions RD.mul_zero.
Print Assumptions RD.mul_succ.
Print Assumptions RD.zero_mul.
Print Assumptions RD.mul_add.
Print Assumptions RD.iso_to_of.
Print Assumptions RD.iso_of_to.
Print Assumptions RD.toNat_inj.
Print Assumptions RD.toNat_add.
Print Assumptions RD.toNat_mul.
Print Assumptions RD.mul_comm.
Print Assumptions RD.mul_assoc.
Print Assumptions RD.mul_one.
Print Assumptions RD.one_mul.
Print Assumptions RD.add_mul.
Print Assumptions RD.le_refl.
Print Assumptions RD.le_trans.
Print Assumptions RD.le_toNat.
Print Assumptions RD.toNat_le.
Print Assumptions RD.le_antisym.
Print Assumptions RD.le_total.
Print Assumptions RD.add_cancel_r.
Print Assumptions RD.lt_toNat.
Print Assumptions RD.lt_irrefl.
Print Assumptions RD.lt_trans.
Print Assumptions RD.lt_trichotomy.
Print Assumptions RD.lt_wf.
Print Assumptions RD.strong_induction.
Print Assumptions RD.eval_hom.
Print Assumptions RD.eqn_transfer.
Print Assumptions RD.evN_ext.
Print Assumptions RD.evD_evN.
Print Assumptions RD.sat_transfer.
Print Assumptions RD.sentence_transfer.
Print Assumptions RD.evD_ext.
Print Assumptions RD.evD_shift.
Print Assumptions RD.evD_subst.
Print Assumptions RD.satD_ext.
Print Assumptions RD.satD_subst.
Print Assumptions RD.consistency.
Print Assumptions RD.prov_sound_N.
Print Assumptions RD.D_validates_induction.
Print Assumptions RD.D_models_PA.
Print Assumptions RD.PA_closed.
Print Assumptions RD.Con_PA.
Print Assumptions RD.PA_true_in_N.
Print Assumptions RD.emb_surj.
Print Assumptions RD.emb_inj.
Print Assumptions RD.categoricity.
Print Assumptions RD.dist_self.
Print Assumptions RD.dist_eq0.
Print Assumptions RD.dist_pos.
Print Assumptions RD.dist_sym.
Print Assumptions RD.dist_tri.
Print Assumptions RD.Betw_id.
Print Assumptions RD.Betw_sym.
Print Assumptions RD.Betw_refl_l.
Print Assumptions RD.dist2_self.
Print Assumptions RD.dist2_eq0.
Print Assumptions RD.dist2_sym.
Print Assumptions RD.dist2_tri.
Print Assumptions RD.zeq_zval.
Print Assumptions RD.zval_z0.
Print Assumptions RD.zval_z1.
Print Assumptions RD.zval_add.
Print Assumptions RD.zval_neg.
Print Assumptions RD.zval_mul.
Print Assumptions RD.zeq_refl.
Print Assumptions RD.zeq_sym.
Print Assumptions RD.zeq_trans.
Print Assumptions RD.zadd_cong.
Print Assumptions RD.zneg_cong.
Print Assumptions RD.zmul_cong.
Print Assumptions RD.zadd_comm.
Print Assumptions RD.zadd_assoc.
Print Assumptions RD.zadd_0_l.
Print Assumptions RD.zadd_neg.
Print Assumptions RD.zmul_comm.
Print Assumptions RD.zmul_assoc.
Print Assumptions RD.zmul_1_l.
Print Assumptions RD.zmul_distrib_l.
Print Assumptions RD.Sum_zero.
Print Assumptions RD.Sum_succ.
Print Assumptions RD.zval_sub.
Print Assumptions RD.zval_Delta.
Print Assumptions RD.FTC_Z.
Print Assumptions RD.FTC.
Print Assumptions RD.FTC_inverse.
Print Assumptions RD.Leibniz.
Print Assumptions RD.injZ_neq0.
Print Assumptions RD.qok_add.
Print Assumptions RD.qok_mul.
Print Assumptions RD.qok_neg.
Print Assumptions RD.qok_inv.
Print Assumptions RD.qval_q0.
Print Assumptions RD.qval_q1.
Print Assumptions RD.qval_add.
Print Assumptions RD.qval_mul.
Print Assumptions RD.qval_neg.
Print Assumptions RD.qeq_refl.
Print Assumptions RD.qeq_sym.
Print Assumptions RD.qeq_trans.
Print Assumptions RD.qadd_comm.
Print Assumptions RD.qadd_assoc.
Print Assumptions RD.qadd_0_l.
Print Assumptions RD.qadd_neg.
Print Assumptions RD.qmul_comm.
Print Assumptions RD.qmul_assoc.
Print Assumptions RD.qmul_1_l.
Print Assumptions RD.qmul_distrib_l.
Print Assumptions RD.qmul_inv.
Print Assumptions RD.two_halves.
Print Assumptions RD.two_halves'.
Print Assumptions RD.inv_mono.
Print Assumptions RD.Qle_lim.
Print Assumptions RD.Qle_lim2.
Print Assumptions RD.Req_refl.
Print Assumptions RD.Req_sym.
Print Assumptions RD.Req_trans.
Print Assumptions RD.Radd_comm.
Print Assumptions RD.Radd_0_l.
Print Assumptions RD.Radd_opp.
Print Assumptions RD.Qarch1.
Print Assumptions RD.Qle_limc.
Print Assumptions RD.Rle_refl.
Print Assumptions RD.Rle_trans.
Print Assumptions RD.close_Req.
Print Assumptions RD.Rle_antisym.
Print Assumptions RD.inj_Q_le.
Print Assumptions RD.Radd_le_mono_r.
Print Assumptions RD.Rlt_irrefl.
Print Assumptions RD.scaleN.
Print Assumptions RD.Rbound.
Print Assumptions RD.Rmul_comm.
Print Assumptions RD.Rmul_1_l.
Print Assumptions RD.IB_pos.
Print Assumptions RD.prod_reg.
Print Assumptions RD.prod_mix.
Print Assumptions RD.IB_scale.
Print Assumptions RD.Rmul_wd.
Print Assumptions RD.inv_idx_le.
Print Assumptions RD.prod_reg2.
Print Assumptions RD.prod_reg2_k.
Print Assumptions RD.Rmul_distrib_l.
Print Assumptions RD.kle1.
Print Assumptions RD.kle3.
Print Assumptions RD.pair_bound.
Print Assumptions RD.tri_bound.
Print Assumptions RD.prod_reg3_k.
Print Assumptions RD.Rmul_assoc.
Print Assumptions RD.frac_split.
Print Assumptions RD.Qarch_c.
Print Assumptions RD.Rlt_le_weak.
Print Assumptions RD.Rlt_trans.
Print Assumptions RD.Rlt_cotrans.
Print Assumptions RD.Rle_max_l.
Print Assumptions RD.Rle_max_r.
Print Assumptions RD.Rmax_lub.
Print Assumptions RD.Rmin_le_l.
Print Assumptions RD.Rmin_le_r.
Print Assumptions RD.Rmin_glb.
Print Assumptions RD.Rconv_const.
Print Assumptions RD.Rlimit_unique.
Print Assumptions RD.Rconv_recip.
Print Assumptions RD.Rdist_self.
Print Assumptions RD.Rdist_sym.
Print Assumptions RD.Rdist_nonneg.
Print Assumptions RD.Rdist_triangle.
Print Assumptions RD.Rabs_Lipschitz.
Print Assumptions RD.Ropp_isometry.
Print Assumptions RD.Radd_Lipschitz.
Print Assumptions RD.Rcontinuous_id.
Print Assumptions RD.Rcontinuous_Rabs.
Print Assumptions RD.soundnessC.
Print Assumptions RD.consistencyC.
Print Assumptions RD.Con_PA_classical.
Print Assumptions RetCenter.orth_expand.
Print Assumptions RetCenter.orth_triple.
Print Assumptions RetCenter.readout_invariant.
Print Assumptions RetCenter.perm_equiv.
Print Assumptions RetCenter.app_perm_proper.
Print Assumptions RetCenter.app_perm_comm.
Print Assumptions RetCenter.app_perm_assoc.
Print Assumptions RetCenter.app_perm_unit.
Print Assumptions RetCenter.nat_le_preorder.
Print Assumptions RetCenter.pole_perm.
Print Assumptions RetCenter.length_perm_inv.
Print Assumptions RetCenter.canonical_readout_invariant.
Print Assumptions RetCenter.canonical_record_lossy.
Print Assumptions RetCenter.box_mono.
Print Assumptions RetCenter.box_K.
Print Assumptions RetCenter.box_nec.
Print Assumptions RetCenter.box_top.
Print Assumptions RetCenter.box_and.
Print Assumptions RetCenter.box_T.
Print Assumptions RetCenter.box_4.
Print Assumptions RetCenter.R_fiber_factive.
Print Assumptions RetCenter.gauge_refines_record.
Print Assumptions RetCenter.R_not_factive_canonical.
Print Assumptions StarRig.adj_is_involution.
Print Assumptions StarRig.sum_mul_lr.
Print Assumptions StarRig.term_eq.
Print Assumptions StarRig.kraus_completeness.
Print Assumptions Gamma.Qplus_nonneg.
Print Assumptions Gamma.Qmul_nonneg.
Print Assumptions Gamma.energy_edge_gauge.
Print Assumptions Gamma.energy_zero_edges.
Print Assumptions Gamma.laplacian_stencil.
Print Assumptions Gamma.secondDiff_quadratic.
Print Assumptions Gamma.secondDiff_readout_invariant.
Print Assumptions ContLimit.sq_neq0.
Print Assumptions ContLimit.D2sym_expand.
Print Assumptions ContLimit.symmetric_second_difference_limit.
Print Assumptions ContLimit.quadratic_symmetric_limit.
Print Assumptions ContReadout.secondDiff_quad_R.
Print Assumptions ContReadout.readout_invariant_R.
Print Assumptions Taylor.d_shift.
Print Assumptions Taylor.d_sq_shift.
Print Assumptions Taylor.d_lin_shift.
Print Assumptions Taylor.d_sqterm.
Print Assumptions Taylor.Gfun_x.
Print Assumptions Taylor.Gfun_xh.
Print Assumptions Taylor.G_deriv.
Print Assumptions Taylor.mvt_pack.
Print Assumptions Taylor.Rabs_ratio_le_1.
Print Assumptions Taylor.taylor_young2.
Print Assumptions Taylor.twice_diff_secondDiff_limit.
Print Assumptions Taylor.G_deriv_at.
Print Assumptions Taylor.mvt_pack_local.
Print Assumptions Taylor.taylor_young2_local.
Print Assumptions Taylor.twice_diff_secondDiff_limit_local.
Print Assumptions Taylor.twice_diff_secondDiff_limit_global.
Print Assumptions Capstone.continuum_gate_readout_native.
Print Assumptions Capstone.continuum_gate_classical_via_readout.
Print Assumptions Capstone.capstone_quadratic_meets.
Print Assumptions InfoOperator.info_is_operator_energy.
Print Assumptions InfoOperator.info_nonneg.
Print Assumptions InfoOperator.info_indistinguishable_zero.
Print Assumptions InfoOperator.info_density_nonneg.
Print Assumptions InfoOperator.info_gauge_invariant.
Print Assumptions InfoOperator.info_form_self_adjoint.
Print Assumptions InfoOperator.info_form_diagonal_is_info.
Print Assumptions InfoOperator.info_form_additive_r.
Print Assumptions InfoOperator.info_form_additive_l.
Print Assumptions InfoOperator.info_form_polarization.
Print Assumptions InfoOperator.green_identity.
Print Assumptions InfoCapstone.info_operator_capstone.
Print Assumptions InfoDynamics.unitary_preserves_norm.
Print Assumptions InfoComplex.unitary_preserves_norm.
Print Assumptions InfoDynamics.qc_unitary_preserves_norm.
Print Assumptions InfoDynamics.unitary_compose.
Print Assumptions InfoLorentz.causal_form_self_adjoint.
Print Assumptions InfoLorentz.causal_form_euclidean_reduction.
Print Assumptions InfoLorentz.causal_form_frame_covariant.
Print Assumptions InfoLorentzContinuum.tends0_opp.
Print Assumptions InfoLorentzContinuum.tends0_plus.
Print Assumptions InfoLorentzContinuum.lorentz_box_continuum.
Print Assumptions InfoLorentzInvariance.boost_preserves_interval.
Print Assumptions InfoLorentzInvariance.box_symbol_boost_invariant.
Print Assumptions InfoLorentzInvariance.box_quad_boost_invariant.
Print Assumptions InfoLorentzTaylor.boost_norm_upper.
Print Assumptions InfoLorentzTaylor.o2_boost.
Print Assumptions InfoLorentzTaylor.box2_boost_invariant.
Print Assumptions InfoEvolution.evolution_identity.
Print Assumptions InfoEvolution.evolution_group.
Print Assumptions InfoEvolution.evolution_preserves_norm.
Print Assumptions InfoHilbertBridge.rot1_norm.
Print Assumptions InfoHilbertBridge.rot1_identity.
Print Assumptions InfoHilbertBridge.rot1_group.
Print Assumptions InfoHilbertBridge.multimode_preserves_norm.
Print Assumptions InfoHilbertBridge.multimode_group.
Print Assumptions InfoSpectral2.sym2_disc_nonneg.
Print Assumptions InfoSpectral2.sym2_eigvec_row1.
Print Assumptions InfoSpectral2.sym2_eigvec_row2.
Print Assumptions InfoSpectral2.sym2_eigvecs_orthogonal.
Print Assumptions InfoDtN.nodeLap_const.
Print Assumptions InfoBio.sis_eigenvalues_real.
Print Assumptions InfoBio.sis_lambda_max_is_root.
Print Assumptions InfoBio.sis_lambda_max_eigenpair.
Print Assumptions InfoBio.sis_instance_R0.
Print Assumptions InfoBio.sis_instance_outbreak.
Print Assumptions InfoBio.logistic_origin.
Print Assumptions InfoBio.logistic_carrying_cap.
Print Assumptions InfoBio.logistic_K_stable.
Print Assumptions InfoBio.logistic_origin_unstable.
Print Assumptions InfoBio.fisher_selection_nonneg.
Print Assumptions InfoFinance.risk_nonneg.
Print Assumptions InfoFinance.discount_relation.
Print Assumptions InfoFinance.variance_instance.
Print Assumptions InfoEcon.market_clears.
Print Assumptions InfoEcon.income_fixed_point.
Print Assumptions InfoEcon.equilibrium_instance.
Print Assumptions InfoEcon.multiplier_instance.
Print Assumptions InfoDomains.network_K3_principal.
Print Assumptions InfoDomains.chem_dominant_growth.
Print Assumptions InfoDomains.cognitive_hitting.
Print Assumptions InfoDomains.thermo_dissipation_nonneg.
Print Assumptions InfoDomains.thermo_dissipation_instance.
Print Assumptions InfoDomains.electrical_tau_RC.
Print Assumptions InfoDomains.ns_reynolds_instance.
Print Assumptions InfoDomains.mhd_energy_nonneg.
Print Assumptions InfoDomains.mhd_energy_instance.
Print Assumptions InfoDomains.nuclear_binding_per_nucleon.
Print Assumptions InfoDomains.cosmo_density_scaling.
Print Assumptions InfoFrontier.spine_discr_nonneg_iff.
Print Assumptions InfoFrontier.spine_lambda_c_char.
Print Assumptions InfoFrontier.spine_split_classical.
Print Assumptions InfoFrontier.spine_split_quantum.
Print Assumptions InfoFrontier.spine_split_boundary.
Print Assumptions InfoFrontier.spine_energy_nonincreasing.
Print Assumptions InfoFrontier.newton_hooke_duality.
Print Assumptions InfoFrontier.newton_hooke_duality_inst.
Print Assumptions InfoFrontier.bohlin_modulus.
Print Assumptions InfoFrontier.total_force_zero_3body.
Print Assumptions InfoFrontier.ns_turbulent_instance.
Print Assumptions InfoFrontier.turbulent_monotone.
Print Assumptions InfoFrontier.kolmogorov_53_from_dimensions.
Print Assumptions InfoFrontier.chaos_divergence_step.
Print Assumptions InfoFrontier.sep_pos.
Print Assumptions InfoFrontier.chaos_divergence_all.
Print Assumptions InfoFrontier.sm_anomaly_cancellation.
Print Assumptions InfoFrontier.sm_cubic_anomaly_cancellation.
Print Assumptions InfoFrontier.schwarzschild_def.
Print Assumptions InfoGR.SchwarzWeak.schwarzschild_def.
Print Assumptions InfoFrontier.schwarzschild_prop_M.
Print Assumptions InfoGR.SchwarzWeak.schwarzschild_prop_M.
Print Assumptions InfoFrontier.schwarzschild_instance.
Print Assumptions InfoFrontier.horizon_area_monotone_in_radius.
Print Assumptions InfoForce.force_is_neg_energy_gradient.
Print Assumptions InfoForce.geometry_force_conservative.
Print Assumptions InfoForce.force_superposition.
Print Assumptions InfoForce.native_roundtrip.
Print Assumptions InfoForce.native_roundtrip'.
Print Assumptions InfoForce.transform_force_eq.
Print Assumptions InfoForce.transform_force_id.
Print Assumptions InfoForce.transform_compose.
Print Assumptions InfoForce.four_forces_one_native.
Print Assumptions InfoInvariant.golden_is_readout_invariant.
Print Assumptions InfoInvariant.golden_fib_invariant.
Print Assumptions InfoInvariant.rg_fixed_is_scale_invariant.
Print Assumptions InfoInvariant.constant_parameter_free_if_invariant.
Print Assumptions InfoGR.SchwarzWeak.schwarzschild_weakfield.
Print Assumptions InfoGR.SchwarzWeak.schwarzschild_gtt_weakfield.
Print Assumptions InfoGR.SchwarzWeak.rs_sun_matches.
Print Assumptions InfoGR.SchwarzWeak.deflection_matches.
Print Assumptions InfoGR.SchwarzWeak.mercury_matches.
Print Assumptions InfoGR.EquivKepler.test_mass_independence.
Print Assumptions InfoGR.EquivKepler.free_fall_same_accel.
Print Assumptions InfoGR.EquivKepler.kepler_omega_sq.
Print Assumptions InfoGR.EquivKepler.kepler_third_law.
Print Assumptions InfoGR.MercuryPrecession.precession_decomposition.
Print Assumptions InfoGR.MercuryPrecession.mercury_precession_matches_measurement.
Print Assumptions InfoGR.MercuryPrecession.mercury_precession_tight.
Print Assumptions InfoGR.LightDeflection.deflection_matches_measurement.
Print Assumptions InfoGR.LightDeflection.newtonian_value.
Print Assumptions InfoGR.LightDeflection.gr_is_twice_newton_general.
Print Assumptions InfoGR.LightDeflection.gr_is_twice_newton.
Print Assumptions InfoGR.SchwarzObservables.redshift_rearrange.
Print Assumptions InfoGR.SchwarzObservables.redshift_sun_matches.
Print Assumptions InfoGR.SchwarzObservables.photon_sphere_ratio.
Print Assumptions InfoGR.SchwarzObservables.isco_ratio.
Print Assumptions InfoGR.SchwarzObservables.escape_at_horizon.
Print Assumptions InfoGR.SchwarzObservables.escape_at_horizon_concrete.
Print Assumptions InfoGR.FlatRotation.rr_nonzero.
Print Assumptions InfoGR.FlatRotation.shell_mass_rate.
Print Assumptions InfoGR.FlatRotation.mass_linear.
Print Assumptions InfoGR.FlatRotation.v_flat.
Print Assumptions InfoGR.FlatRotation.v_independent_of_r.
Print Assumptions InfoGR2.GW.pw_coeffs.
Print Assumptions InfoGR2.GW.gw_box_of_plane.
Print Assumptions InfoGR2.GW.gw_wave_equation.
Print Assumptions InfoGR2.GW.gw_wave_equation_neg.
Print Assumptions InfoGR2.GW.gw_null_iff_lightspeed.
Print Assumptions InfoGR2.GW.gw_null_all_frames.
Print Assumptions InfoGR2.ShapiroLink.shapiro_leading_from_rs.
Print Assumptions InfoGR2.GeodesicLink.geodesic_mass_independence.
Print Assumptions InfoGR2.KerrLink.kerr_horizon_no_spin_is_rs.
Print Assumptions InfoCosmoEquilibrium.spine_equilibrium_iff_rest.
Print Assumptions InfoGreen.flux_radius_independent.
Print Assumptions InfoGreen.green_coefficient_relation.
Print Assumptions InfoGreen.green_4pi.
Print Assumptions InfoGreen.green_4pi_value.
Print Assumptions InfoEinsteinEntropy.eight_pi_is_two_four_pi.
Print Assumptions InfoEinsteinEntropy.einstein_coupling_factor.
Print Assumptions InfoEinsteinEntropy.einstein_factor_from_green.
Print Assumptions InfoEinsteinEntropy.einstein_green_coefficient.
Print Assumptions InfoEinsteinEntropy.quarter_is_twopi_over_eightpi.
Print Assumptions InfoEinsteinEntropy.quarter_via_four_pi.
Print Assumptions InfoEinsteinEntropy.entropy_area_quarter_from_ratio.
Print Assumptions InfoPlanckRel.ell_P_sq_relation.
Print Assumptions InfoPlanckRel.m_P_sq_relation.
Print Assumptions InfoPlanckRel.planck_action_identity.
Print Assumptions InfoPlanckRel.ell0_is_planck.
Print Assumptions InfoJacobson.jacobson_8piG_emerges.
Print Assumptions InfoJacobson.jacobson_hbar_cancels.
Print Assumptions InfoCharge.charge_up.
Print Assumptions InfoCharge.charge_down.
Print Assumptions InfoCharge.charge_electron.
Print Assumptions InfoCharge.charge_neutrino.
Print Assumptions InfoCharge.charge_ratio_ud.
Print Assumptions InfoCharge.gluons.
Print Assumptions InfoCharge.weak_bosons.
Print Assumptions InfoCharge.total_gauge_bosons.
Print Assumptions InfoRelational.mass_ratio_is_inverse_tau_ratio.
Print Assumptions InfoRelational.mass_ratio_indep_hbar_c.
Print Assumptions InfoRelational.mass_ratio_is_spectral_ratio.
Print Assumptions InfoRelational.mixing_symmetric.
Print Assumptions InfoRelational.mixing_orthogonal_no_mixing.
Print Assumptions InfoSoliton.bps_ratio_is_charge_ratio.
Print Assumptions InfoSoliton.kink_coeff_squared.
Print Assumptions InfoSoliton.scale_ratio_is_tunable.
Print Assumptions InfoTelegraph.telegraph_damping_removed.
Print Assumptions InfoTelegraph.kg_mass_is_half_damping.
Print Assumptions InfoTelegraph.kg_mass_squared.
Print Assumptions InfoTelegraph.mass_memory_duality.
Print Assumptions InfoTelegraph.memory_factor_collapses_to_half.
Print Assumptions InfoSpineMass.spine_damping_removed.
Print Assumptions InfoSpineMass.spine_mass_is_half_ratio.
Print Assumptions InfoSpineMass.spine_memory_mass_product.
Print Assumptions InfoSpineMass.spine_mass_ratio_invariant.
Print Assumptions InfoPotential.potential_Z2_symmetric.
Print Assumptions InfoPotential.vprime_factored.
Print Assumptions InfoPotential.vacuum_is_equilibrium.
Print Assumptions InfoPotential.vacuum_binding_energy.
Print Assumptions InfoPotential.origin_above_vacuum.
Print Assumptions InfoMassChain.mass_chain_connected.
Print Assumptions InfoEinsteinTensor.einstein_trace.
Print Assumptions InfoEinsteinTensor.vacuum_is_ricci_flat.
Print Assumptions InfoEinsteinTensor.trace_reverse_equiv.
Print Assumptions InfoEinsteinTensor.conservation_from_bianchi.
Print Assumptions InfoJacobianCovariance.einstein_general_covariance.
Print Assumptions InfoJacobianCovariance.jacobian_compose.
Print Assumptions InfoJacobianCovariance.transform_identity.
Print Assumptions InfoChristoffel.christoffel_lower_symmetric.
Print Assumptions InfoChristoffel.metric_compatibility.
Print Assumptions InfoChristoffel.riemann_antisym_last_pair.
Print Assumptions InfoChristoffel.first_bianchi.
Print Assumptions InfoChristoffel.second_bianchi_leading.
Print Assumptions InfoActionQuantum.hbar_from_minimal_cell.
Print Assumptions InfoActionQuantum.hbar_is_energy_memory.
Print Assumptions InfoActionQuantum.h_per_cycle_is_2pi.
Print Assumptions InfoSchrodinger.spine_mode_dispersion.
Print Assumptions InfoSchrodinger.energy_spectrum_from_laplacian.
Print Assumptions InfoSchrodinger.energy_nonneg_from_psd.
Print Assumptions InfoDecoherence.dissipative_relaxation.
Print Assumptions InfoDecoherence.decoherence_rate_from_gap.
Print Assumptions InfoDecoherence.decoherence_rate_positive.
Print Assumptions InfoDecoherence.decoherence_memory_product.
Print Assumptions InfoUncertainty.ladder_commutator.
Print Assumptions InfoUncertainty.ladder_noncommuting.
Print Assumptions InfoUncertainty.uncertainty_robertson.
Print Assumptions InfoUncertainty.heisenberg_bound.
Print Assumptions InfoBorn.born_prob_nonneg.
Print Assumptions InfoBorn.born_valid_distribution.
Print Assumptions InfoBorn.born_prob_bounded.
Print Assumptions InfoBorn.born_expectation_convex.
Print Assumptions InfoQuantumGravity.qg_unification.
Print Assumptions InfoComplex.i_squared.
Print Assumptions InfoComplex.modsq_nonneg.
Print Assumptions InfoComplex.modsq_mult.
Print Assumptions InfoDeepClosings.discrete_clairaut.
Print Assumptions InfoDeepClosings.born_is_energy_fraction.
Print Assumptions InfoTauFloor.discrete_rate_ceiling.
Print Assumptions InfoTauFloor.continuum_no_floor.
Print Assumptions InfoStandardModel.sm_u1_cubic_anomaly.
Print Assumptions InfoStandardModel.sm_grav_anomaly.
Print Assumptions InfoStandardModel.sm_su2_u1_anomaly.
Print Assumptions InfoStandardModel.sm_su3_u1_anomaly.
Print Assumptions InfoStandardModel.sm_witten_even.
Print Assumptions InfoGraviton.graviton_dispersion.
Print Assumptions InfoGraviton.graviton_dynamical.
Print Assumptions InfoHypothesisSeeds.u1_group_closure.
Print Assumptions InfoHypothesisSeeds.energy_uv_bounded.
Print Assumptions InfoUniversalEquation.domain_rescale_covariant.
Print Assumptions InfoUniversalEquation.domain_invariant_zero.
Print Assumptions InfoUniversalEquation.domain_superposition.
Print Assumptions InfoCascade.cascade_conserves_energy.
Print Assumptions InfoCascade.triad_transfer_balance.
